---
title: "Chirstophe Datasets"
author: "Elijah Willie"
date: "16/02/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(Matrix)
  library(Rcpp)
  library(DuoClustering2018)
  library(SIMLR)
  library(pcurve)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
source("run_CIDR.R")
source("run_RaceID3.R")
source("run_TSCAN.R")
source("run_Ascend.R")
source("run_Monocle.R")
source("run_pcaReduce.R")
source("run_Sincell.R")
source("run_sscClust.R")
source("Seurat_Mod.R")
source("Ascend_Mod.R")
source("SC3_Mod.R")
source("run_sscClustMod.R")
source("TSCAN_Mod.R")
source("Monocle_Mod.R")
source("r_autoencoder.R")
source("~/Documents/Spectrum/R/core_functions.R")
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
```

D7 GP66
```{r}
# read in the matrix
matrix_dir = "/home/elijah/Documents/Clusterability/Data/Christophe_Data/Virus_Specfic/D7_WT/"

expression_matrix <- Read10X(data.dir = matrix_dir)

seurat_object = CreateSeuratObject(counts = expression_matrix, project = "Proj", min.cells = 2, min.features = 500)
seurat_object[["percent.mt"]] <- Seurat::PercentageFeatureSet(seurat_object, pattern = "^mt-")
# subset the data
seurat_object <- subset(seurat_object, subset = nFeature_RNA > 0 & nFeature_RNA > 0 & percent.mt < 10)
counts <- seurat_object@assays$RNA@counts

obj <- CreateModalityObject(counts)

obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# compute Distances
# obj <- ComputeDistances(obj)
# obj <- ComputeDistances(obj, method = "Scrna")
# obj <- ComputeDistances(obj, method = "SCTransform")


# k.seurat <- EstimateK(obj)
# k.scrna <- EstimateK(obj, method = "Scrna")
# k.sct <- EstimateK(obj, method = "SCTransform")
# # k.randomly <- .estkTW(obj@Randomly$Scaled.Data)
# k.final <- max(k.seurat, k.scrna, k.sct)
# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

Log <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
Multinom <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
res.dip <- cbind(Log, Multinom, NegBinom)
colnames(res.dip) <- c("Log", "Multinom", "NegBinom")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))

obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="Ciucci et al Fig 1B Dip Heatmap",
                                    display_numbers = T, number_color = "black")
p.dip <- ggplotify::as.ggplot(obj.heatmap)

Clusters <- ensemble.labs
Ensemble.Clusters <- as.factor(ensemble.labs)
Multiview.Clusters <- as.factor(obj@Labels$All)

evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Ensemble.Clusters)) + 
    labs(title = paste("Ciucci et al Fig 1B Ensemble Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.multiview <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Multiview.Clusters)) + 
    labs(title = paste("Ciucci et al Fig 1B Multiview Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- Seurat::NormalizeData(object = seurat_object, normalization.method = "LogNormalize", scale.factor = 10000)
# VariableFeatures(obj) <- rownames(data)
obj <- Seurat::FindVariableFeatures(obj, selection.method = "vst", verbose = F)
obj <- Seurat::ScaleData(object = obj, features = rownames(obj@assays$RNA@data), verbose = T)
obj <- Seurat::RunPCA(obj, features = VariableFeatures(object = obj), npcs = k.seurat, verbose = F)
obj <- Seurat::FindNeighbors(obj, reduction="pca", dims = 1:k.seurat, k.param = 30)
obj <- Seurat::FindClusters(obj, resolution = 0.8, random.seed = 1994)
Seurat.Clusters <- Seurat::Idents(obj) 
p.seurat <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Seurat.Clusters)) + 
    labs(title = paste("Ciucci et al Fig 1B Seurat Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.dip, p.evecs, p.multiview, p.seurat, labels = c("A", "B", "C", "D"))
# res.seurat <- run_Seurat(as.matrix(obj@Data$cleaned))
```


Arazi et al
```{r}
counts <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Kidney/exprMatrix.tsv", nThread = 12) %>% column_to_rownames(var = "gene")

meta.data <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Kidney/meta.csv")
meta.data <- meta.data[-1, ]
# meta.data <- column_to_rownames(meta.data, var = "NAME")

t <- grep("CT", meta.data$Cluster)
res <- meta.data$NAME[t]
counts_new <- counts[, res]
Paper_Clusters <- meta.data$Cluster[t]

obj <- CreateModalityObject(as.matrix((round(counts_new))), sparse = FALSE)

obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# compute Distances
# obj <- ComputeDistances(obj)
# obj <- ComputeDistances(obj, method = "Scrna")
# obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- EstimateK(obj)
k.scrna <- EstimateK(obj, method = "Scrna")
k.sct <- EstimateK(obj, method = "SCTransform")
# k.randomly <- .estkTW(obj@Randomly$Scaled.Data)
k.final <- max(k.seurat, k.scrna, k.sct)
# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

Log <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
Multinom <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
res.dip <- cbind(Log, Multinom, NegBinom)
colnames(res.dip) <- c("Log", "Multinom", "NegBinom")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))

obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="Arazi et al Fig 4 Dip Heatmap",
                                    display_numbers = T, number_color = "black")
p.dip <- ggplotify::as.ggplot(obj.heatmap)

Ensemble.Clusters <- as.factor(ensemble.labs)
Multiview.Clusters <- as.factor(obj@Labels$All)

evecs <- as.data.frame(obj@Seurat$Sig.PCs.Data)
colnames(evecs) <- c("PC1", "PC2")
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Ensemble.Clusters)) + 
    labs(title = paste("Arazi et al Fig 4 Ensemble Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.multiview <- ggplot(evecs) + geom_point(aes(x = PC1, y = PC2, color = Multiview.Clusters)) + 
    labs(title = paste("Freytag et al Gold Standard Multiview Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# obj <- Seurat::NormalizeData(object = obj@Seurat$obj, normalization.method = "LogNormalize", scale.factor = 10000)
# VariableFeatures(obj) <- rownames(data)
# obj <- Seurat::FindVariableFeatures(obj, selection.method = "vst", verbose = F)
# obj <- Seurat::ScaleData(object = obj, features = rownames(obj@assays$RNA@data), verbose = T)
# obj <- Seurat::RunPCA(obj, features = VariableFeatures(object = obj), npcs = k.seurat, verbose = F)
obj <- Seurat::FindNeighbors(obj@Seurat$obj, reduction="pca", dims = 1:k.seurat, k.param = 30)
obj <- Seurat::FindClusters(obj, resolution = 0.8, random.seed = 1994)
Seurat.Clusters <- Seurat::Idents(obj) 
p.seurat <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Seurat.Clusters)) + 
    labs(title = paste("Arazi et al Fig 4 Seurat Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))


p.labs <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Paper_Clusters)) + 
    labs(title = paste("Arazi et al Fig 4 Paper Clusters,")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.dip, p.evecs, p.multiview, p.labs, labels = c("A", "B", "C", "D"))
```


Tibbitt  
```{r}
counts <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Dust_Mites/GSE131935_SS2_15_0160_rpkms.tab", header = TRUE) %>% distinct()
counts$gene <- make.unique(as.character(counts$gene))
counts <- column_to_rownames(counts, var = "gene")

# %>% column_to_rownames(var = "gene")
# Coutns_1 <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Dust_Mites/GSE131935_SS2_17_218_rpkms_.tab", nThread = 12)
# counts_2 <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Dust_Mites/GSE131935_SS2_17_449_rpkms.tab", nThread = 12)
obj <- CreateModalityObject(as.matrix(round(counts)), sparse = FALSE)

obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# compute Distances
# obj <- ComputeDistances(obj)
# obj <- ComputeDistances(obj, method = "Scrna")
# obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- EstimateK(obj)
k.scrna <- EstimateK(obj, method = "Scrna")
k.sct <- EstimateK(obj, method = "SCTransform")
# k.randomly <- .estkTW(obj@Randomly$Scaled.Data)
k.final <- max(k.seurat, k.scrna, k.sct)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = 10)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct)
obj <- ComputeTransformations(obj, method = "All", ncomp = 10)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

Log <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
Multinom <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
res.dip <- cbind(Log, Multinom, NegBinom)
colnames(res.dip) <- c("Log", "Multinom", "NegBinom")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))

Ensemble.Clusters <- as.factor(ensemble.labs)
Multiview.Clusters <- as.factor(obj@Labels$All)

obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="Tibbitt et al Fig 1C Dip Heatmap",
                                    display_numbers = T, number_color = "black")
p.dip <- ggplotify::as.ggplot(obj.heatmap)

evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x =tSNE_1, y = tSNE_2, color = Ensemble.Clusters)) + 
    labs(title = paste("Tibbitt et al Fig 1C Ensemble Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- Seurat::FindNeighbors(obj@Seurat$obj, reduction="pca", dims = 1:k.seurat, k.param = 30)
obj <- Seurat::FindClusters(obj, resolution = 0.8, random.seed = 1994)
Seurat.Clusters <- Seurat::Idents(obj) 

p.seurat <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Seurat.Clusters)) + 
    labs(title = paste("Tibbitt et al Fig 1C Seurat Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.multiview <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Multiview.Clusters)) + 
    labs(title = paste("Tibbitt et al Fig 1C Multiview Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.dip, p.evecs, p.multiview, p.seurat, labels = c("A", "B", "C", "D"))

```


Yost
```{r}
counts <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Tumor_infiltrating/bcc_scRNA_counts_new.csv",nThread = 12)
counts <- column_to_rownames(counts, var = "V1")
counts_sampled <- counts[, sample(ncol(counts), 10000)]
gc()
# counts_new <- Matrix(as.matrix(counts), sparse = TRUE)  

meta.data <- fread("/home/elijah/Documents/Clusterability/Data/Christophe_Data/Tumor_infiltrating/bcc_all_metadata.txt", nThread = 12)
clusters <- meta.data$cluster[meta.data$cell.id %in% colnames(counts_sampled)]
Paper_Clusters <- as.factor(clusters)
UMAP1 <- meta.data$UMAP1[meta.data$cell.id %in% colnames(counts_sampled)]
UMAP2 <- meta.data$UMAP2[meta.data$cell.id %in% colnames(counts_sampled)]
coords <- as.data.frame(cbind(UMAP1, UMAP2))
# cell.ids <- meta.data$cell.id[meta.data$cluster %in% c("CD4_T_cells", "CD8_ex_T_cells", "Tregs", "NK_cells", "CD8_mem_T_cells", "CD8_act_T_cells", "Tcell_prolif")]

# "Tregs", "NK", "CD8_mem_T_cells", "CD8_act_T_cells", "Tcell_prolif"
# counts_new <- counts[, cell.ids]
  
obj <- CreateModalityObject(counts = as.matrix(counts_sampled))
gc()
obj <- PreprocessObject(obj,  nFeatures = 500)
gc()
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
gc()
obj <- PreprocessObject(obj,  method = "Scrna", nFeatures = 500)


k.seurat <- EstimateK(obj)
k.scrna <- EstimateK(obj, method = "Scrna")
k.sct <- EstimateK(obj, method = "SCTransform")
# k.randomly <- .estkTW(obj@Randomly$Scaled.Data)
k.final <- max(k.seurat, k.scrna, k.sct)

obj <- ComputeTransformations(obj)
gc()
obj <- ComputeTransformations(obj, method = "Scrna")
gc()
obj <- ComputeTransformations(obj, method = "SCTransform")
gc()
obj <- ComputeTransformations(obj, method = "All")

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

Log <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
Multinom <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
res.dip <- cbind(Log, Multinom, NegBinom)
colnames(res.dip) <- c("Log", "Multinom", "NegBinom")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
# ensemble.labs <- diceR::LCA(ensemble.mat)
  
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="Yost et al Fig 1E Dip Heatmap",
                                    display_numbers = T, number_color = "black")
p.dip <- ggplotify::as.ggplot(obj.heatmap)

# Clusters <- ensemble.labs
Ensemble.Clusters <- as.factor(ensemble.labs)
Multiview.Clusters <- as.factor(obj@Labels$All)

evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Ensemble.Clusters)) + 
    labs(title = paste("Yost et al Fig 1E Ensemble Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.multiview <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Multiview.Clusters)) + 
    labs(title = paste("Yost et al Fig 1E Multiview Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.labs <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Paper_Clusters)) + 
    labs(title = paste("Yost et al Fig 1E Paper Clusters,")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- Seurat::FindNeighbors(obj@Seurat$obj, reduction="pca", dims = 1:2, k.param = 30)
obj <- Seurat::FindClusters(obj, resolution = 0.8, random.seed = 1994)
Seurat.Clusters <- Seurat::Idents(obj) 

p.seurat <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Seurat.Clusters)) + 
    labs(title = paste("Yost et al Fig 1E Seurat Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.paper <-  ggplot(coords) + geom_point(aes(x = UMAP1, y = UMAP2, color = Paper_Clusters)) + 
    labs(title = paste("Yost et al Fig 1E Paper Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.dip, p.evecs, p.multiview, p.labs, p.seurat, p.paper, labels = c("A", "B", "C", "D", "E", "F"))
```

