---
title: "Cluster Analysis"
author: "Elijah Willie"
date: "08/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required librares
```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  }
)
# source required functions
setwd("/home/elijah/Documents/Clusterability/scripts")
source("Helper_Functions.R")
source("/home/elijah/Documents/scrna2019/algs/glmpca.R")
source("/home/elijah/Documents/scrna2019/util/functions.R")
source("/home/elijah/Documents/scrna2019/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("func.R")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
use_python("/usr/local/bin/python3")
```

# Freytag et al
## Gold standard dataset
```{r}
# load in the dataset
load("../Datasets/Sce_CellRanger.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))

sce <- scater::normalize(sce)
p.gold.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Gold Standard PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)


obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <- TestModality(obj, type = "SCTransform")
# compute a result table for all the tests
seurat <- as.data.frame(unlist(obj@Tests$Seurat))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform))
colnames(sctransfrom) <- c("SCTransform.Dip.")

scrna <- as.data.frame(unlist(obj@Tests$Scrna))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, breaks = c(0, 0.05, 1), color = c("lightblue", "gray"), main = paste("Heatmap"))
heatmap <- ggplotify::as.ggplot(obj.heatmap)

seurat_pca_df <- as.data.frame(obj@Seurat$Sig.PCs.Data[, 1:2])
scrna_pca_df <- as.data.frame(obj@Scrna$Sig.PCs.Data[, 1:2])

# Run PCA
p.pca <- ggplot(seurat_pca_df) + geom_point(aes(PC_1, PC_2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Seurat PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))
p.pca.scrna <- ggplot(scrna_pca_df) + geom_point(aes(PC1, PC2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Scrna PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))

# Plot the Tsne
seurat.tsne <- as.data.frame(obj@Seurat$Tsne.Data)
p.seurat.tsne <-  ggplot(seurat.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.tsne <- as.data.frame(obj@Scrna$Tsne.Data)
p.scrna.tsne <-  ggplot(scrna.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot UMAP
seurat.umap <- as.data.frame(obj@Seurat$Umap.Data)
p.seurat.umap <- ggplot(seurat.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.umap <- as.data.frame(obj@Scrna$Umap.Data)
p.scrna.umap <- ggplot(scrna.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))


# combine the plots
plots <- plot_grid(p.pca, p.pca.scrna, p.seurat.tsne, p.scrna.tsne, 
                       p.seurat.umap, p.scrna.umap,
                   heatmap, labels = c("A", "B","C", "D", "E", "F","G", "H"))


sce <- SingleCellExperiment(
    assays = list(counts = obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)

sce@metadata$sc3
 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F)

res.gold.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.gold.clustering <- t(as.data.frame(res.gold.clustering))
colnames(res.gold.clustering) <- c("Gold")
res.gold.clustering <- as.data.frame(res.gold.clustering)
res.gold.clustering <- setDT(res.gold.clustering, keep.rownames = T)[]
colnames(res.gold.clustering) <- c("Method", "AdjustedRandIndex")

p.gold.bar <- res.gold.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor", T, F)) dplyr::%>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Fretag et al Gold Standard BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

## Silver datasets
```{r}
# load in the dataset
load("../Datasets/Sce_Dataset2.RData")
meta.data <- colData(sce)


sce <- scater::normalize(sce)
p.silver1.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver2 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

silver.counts <- counts(sce)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), meta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
trueLabels <- as.numeric(as.factor(meta.data$Truth))
# run it through the pipeline
obj <- CreateModalityObject(silver.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

gc()
counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)

sce <- scater::normalize(sce)
sce <- sc3_estimate_k(sce)

sce@metadata$sc3

rowData(sce)$feature_symbol <- rownames(sce)
sce <- sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.silver.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.silver.clustering <- t(as.data.frame(res.silver.clustering))
colnames(res.silver.clustering) <- c("Silver")

res.silver.clustering <- as.data.frame(res.silver.clustering)
res.silver.clustering <- setDT(res.silver.clustering, keep.rownames = T)[]
colnames(res.silver.clustering) <- c("Method", "AdjustedRandIndex")
p.silver.bar <- res.silver.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam', T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Fretag et al Silver2 Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

# Simulations
## Cluster Overlap

```{r}
params.groups <- newSplatParams(batchCells = 1000, nGenes = 3000, seed = 1994)

# run simulations
sim <- splatSimulateGroups(params.groups, group.prob = c(1/3, 1/3, 1/3), de.facLoc = c(1,1,1)*0.1,
                             de.facScale = c(1,1,1)*0.1, verbose = FALSE)
meta.data <- colData(sim)
trueLabels <- as.numeric(as.factor(meta.data$Group))
sim <- scater::normalize(sim)
p.sim.0.1 <- scater::plotPCA(sim, colour_by = "Group") + theme_grey() + ggtitle("PCA plot of 3 groups with cluster overlap of 0.1") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# extract the counts
sim_counts <- counts(sim)

# run the pipeline
obj <- CreateModalityObject(sim_counts)

# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")

# compute a result table for all the tests
seurat <- as.data.frame(unlist(obj@Tests$Seurat))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

scrna <- as.data.frame(unlist(obj@Tests$Scrna))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat)
colnames(res.table) <- c("Seurat", "Scrna")

# plot heat map
obj.heatmap <- pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, breaks = c(0, 0.05, 1), color = c("lightblue", "gray"), main = paste("Heatmap"))
heatmap <- as.ggplot(obj.heatmap)
heatmap <- as.ggplot(obj.heatmap)

seurat_pca_df <- as.data.frame(obj@Seurat$Sig.PCs.Data[, 1:2])
scrna_pca_df <- as.data.frame(obj@Scrna$Sig.PCs.Data[, 1:2])

# Run PCA
p.pca <- ggplot(seurat_pca_df) + geom_point(aes(PC_1, PC_2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Seurat PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))
p.pca.scrna <- ggplot(scrna_pca_df) + geom_point(aes(PC1, PC2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Scrna PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))

# Plot the Tsne
seurat.tsne <- as.data.frame(obj@Seurat$Tsne.Data)
p.seurat.tsne <-  ggplot(seurat.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.tsne <- as.data.frame(obj@Scrna$Tsne.Data)
p.scrna.tsne <-  ggplot(scrna.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot UMAP
seurat.umap <- as.data.frame(obj@Seurat$Umap.Data)
p.seurat.umap <- ggplot(seurat.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.umap <- as.data.frame(obj@Scrna$Umap.Data)
p.scrna.umap <- ggplot(scrna.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))


# combine the plots
plots <- plot_grid(p.pca, p.pca.scrna, p.seurat.tsne, p.scrna.tsne, 
                       p.seurat.umap, p.scrna.umap,
                   heatmap, labels = c("A", "B","C", "D", "E", "F","G", "H"))

rowData(sim)$feature_symbol <- rownames(sim)
sim <- sc3(sim, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.sim.clustering.0.1 <- .ClusterDat(obj, sim, length(unique(trueLabels)), trueLabels)
res.sim.clustering.0.1 <- t(as.data.frame(res.sim.clustering.0.1))
colnames(res.sim.clustering.0.1) <- c("0.10")

res.sim.clustering.0.1 <- as.data.frame(res.sim.clustering.0.1)
res.sim.clustering.0.1 <- setDT(res.sim.clustering.0.1, keep.rownames = T)[]
colnames(res.sim.clustering.0.1) <- c("Method", "AdjustedRandIndex")
p.sim.bar <- res.sim.clustering.0.1 %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "3 groups with cluster overlap of 0.1 Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```


```{r}
params.groups <- newSplatParams(batchCells = 1000, nGenes = 3000, seed = 1994)

# run simulations
sim <- splatSimulateGroups(params.groups, group.prob = c(1/3, 1/3, 1/3), de.facLoc = c(1,1,1)*0.15,
                             de.facScale = c(1,1,1)*0.15, verbose = FALSE)
meta.data <- colData(sim)
trueLabels <- as.numeric(as.factor(meta.data$Group))
sim <- scater::normalize(sim)
p.sim.0.15 <- scater::plotPCA(sim, colour_by = "Group") + theme_grey() + ggtitle("PCA plot of 3 groups with cluster overlap of 0.15") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# extract the counts
sim_counts <- counts(sim)

# run the pipeline
obj <- CreateModalityObject(sim_counts)

# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

rowData(sim)$feature_symbol <- rownames(sim)
sim <- sc3(sim, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.sim.clustering.0.15 <- .ClusterDat(obj, sim, length(unique(trueLabels)), trueLabels)
res.sim.clustering.0.15 <- t(as.data.frame(res.sim.clustering.0.15))
colnames(res.sim.clustering.0.15) <- c("0.15")
```

#
```{r}
params.groups <- newSplatParams(batchCells = 1000, nGenes = 3000, seed = 1994)

# run simulations
sim <- splatSimulateGroups(params.groups, group.prob = c(1/3, 1/3, 1/3), de.facLoc = c(1,1,1)*0.20,
                             de.facScale = c(1,1,1)*0.20, verbose = FALSE)
meta.data <- colData(sim)
trueLabels <- as.numeric(as.factor(meta.data$Group))
sim <- scater::normalize(sim)
p.sim.0.2 <- scater::plotPCA(sim, colour_by = "Group") + theme_grey() + ggtitle("PCA plot of 3 groups with cluster overlap of 0.20") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# extract the counts
sim_counts <- counts(sim)

# run the pipeline
obj <- CreateModalityObject(sim_counts)

# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

rowData(sim)$feature_symbol <- rownames(sim)
sim <- sc3(sim, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.sim.clustering.0.20 <- .ClusterDat(obj, sim, length(unique(trueLabels)), trueLabels)
res.sim.clustering.0.20 <- t(as.data.frame(res.sim.clustering.0.20))
colnames(res.sim.clustering.0.20) <- c("0.20")

```

## Generate bar plot
```{r}
res.clustering.sim <- cbind(res.sim.clustering.0.1, res.sim.clustering.0.15, res.sim.clustering.0.20)
res.clustering.sim <- as.data.frame(res.clustering.sim)
res.clustering.sim <- setDT(res.clustering.sim, keep.rownames = T)[]
res.clustering.sim.melted <- melt(res.clustering.sim, id.vars = "rn")
colnames(res.clustering.sim.melted) <- c("Method", "Dataset", "AdjustedRand")
p.sim.bar <- res.clustering.sim.melted %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' , T, F)) %>% 
  ggplot(aes(Method, AdjustedRand)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Cluster Overlap Simulation Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90)) +
  facet_grid(. ~ Dataset)
```


## Combine all the plots
```{r}
pca.plots <- plot_grid(p.sim.0.1, p.sim.0.15, p.sim.0.2, labels = c("A", "B", "C"))

# save plots to pdf
pdf("../Results/Pipeline/Paper_Plots/Cluster_Analysis_Sim_Cluster_Overlap_Plots.pdf", height = 10, width = 12)
plot(pca.plots)
plot(p.sim.bar)
dev.off()
```

## load in the preprocessed data
```{r}
pbmc <- readRDS(file = "../Data/Benchmarks/pbmc3k_final.rds")

p.pbmc.umap <- DimPlot(pbmc, reduction = "umap") + ggtitle("PBMC Clusters")  + 
                                                                    theme_grey() +  theme(plot.title = element_text(hjust = 0.5))


pbmc.counts <- as.matrix(GetAssayData(pbmc, slot = "counts"))
meta.data <- as.data.frame(Idents(pbmc))
counts.sampled <- pbmc.counts[, sample(ncol(pbmc.counts), 2500)]
sampled.indices <- match(colnames(counts.sampled), rownames(meta.data))
trueLabels <- as.numeric(as.factor(meta.data$`Idents(pbmc)`))

# run it through the pipeline
obj <- CreateModalityObject(pbmc.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

gc()
counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sce <- sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.pbmc.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.pbmc.clustering <- t(as.data.frame(res.pbmc.clustering))
colnames(res.pbmc.clustering) <- c("PBMC")

res.pbmc.clustering <- as.data.frame(res.pbmc.clustering)
res.pbmc.clustering <- setDT(res.pbmc.clustering, keep.rownames = T)[]
colnames(res.pbmc.clustering) <- c("Method", "AdjustedRandIndex")
p.pbmc.bar <- res.pbmc.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "PBMC 3K Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

# Romanov
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Brain/romanov.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
romanov.counts <- counts(sce)

obj <- CreateModalityObject(romanov.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
obj <- PreprocessObject(obj, method = "SCTransform")
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

gc()
counts.new <- obj@Data$cleaned
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = 500)

res.romanov.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)


res.romanov.clustering <- t(as.data.frame(res.romanov.clustering))
colnames(res.romanov.clustering) <- c("PBMC")

```

# Zeisel
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Brain/zeisel.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
zeisel.counts <- counts(sce)

p.zeisel.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Zeisel et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(zeisel.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")

# compute a result table for all the tests
seurat <- as.data.frame(unlist(obj@Tests$Seurat))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

scrna <- as.data.frame(unlist(obj@Tests$Scrna))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat)
colnames(res.table) <- c("Seurat", "Scrna")

# plot heat map
obj.heatmap <- pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, breaks = c(0, 0.05, 1), color = c("lightblue", "gray"), main = paste("Heatmap"))
heatmap <- as.ggplot(obj.heatmap)

seurat_pca_df <- as.data.frame(obj@Seurat$Sig.PCs.Data[, 1:2])
scrna_pca_df <- as.data.frame(obj@Scrna$Sig.PCs.Data[, 1:2])

# Run PCA
p.pca <- ggplot(seurat_pca_df) + geom_point(aes(PC_1, PC_2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Seurat PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))
p.pca.scrna <- ggplot(scrna_pca_df) + geom_point(aes(PC1, PC2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Scrna PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))

# Plot the Tsne
seurat.tsne <- as.data.frame(obj@Seurat$Tsne.Data)
p.seurat.tsne <-  ggplot(seurat.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.tsne <- as.data.frame(obj@Scrna$Tsne.Data)
p.scrna.tsne <-  ggplot(scrna.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot UMAP
seurat.umap <- as.data.frame(obj@Seurat$Umap.Data)
p.seurat.umap <- ggplot(seurat.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.umap <- as.data.frame(obj@Scrna$Umap.Data)
p.scrna.umap <- ggplot(scrna.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))


# combine the plots
plots <- plot_grid(p.pca, p.pca.scrna, p.seurat.tsne, p.scrna.tsne, 
                       p.seurat.umap, p.scrna.umap,
                   heatmap, labels = c("A", "B","C", "D", "E", "F","G", "H"))

gc()
counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sce <- sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.zeisel.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.zeisel.clustering <- t(as.data.frame(res.zeisel.clustering))
colnames(res.zeisel.clustering) <- c("Zeisel")

res.zeisel.clustering <- as.data.frame(res.zeisel.clustering)
res.zeisel.clustering <- setDT(res.zeisel.clustering, keep.rownames = T)[]
colnames(res.zeisel.clustering) <- c("Method", "AdjustedRandIndex")
p.zeisel.bar <- res.zeisel.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor" , T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Zeisel et al Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

# Klein
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Embryo_Stem_Cells/klein.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
klein.counts <- counts(sce)

p.klein.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Klein et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(klein.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

gc()
counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sce <- sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.klein.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.klein.clustering <- t(as.data.frame(res.klein.clustering))
colnames(res.klein.clustering) <- c("klein")

res.klein.clustering <- as.data.frame(res.klein.clustering)
res.klein.clustering <- setDT(res.klein.clustering, keep.rownames = T)[]
colnames(res.klein.clustering) <- c("Method", "AdjustedRandIndex")
p.klein.bar <- res.klein.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' , T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "klein et al Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

# Deng Reads
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Embryo_Development/deng-reads.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
deng.counts <- counts(sce)

p.deng.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Deng et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(deng.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")

# compute a result table for all the tests
seurat <- as.data.frame(unlist(obj@Tests$Seurat))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

scrna <- as.data.frame(unlist(obj@Tests$Scrna))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat)
colnames(res.table) <- c("Seurat", "Scrna")

# plot heat map
obj.heatmap <- pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, breaks = c(0, 0.05, 1), color = c("lightblue", "gray"), main = paste("Heatmap"))
heatmap <- as.ggplot(obj.heatmap)

seurat_pca_df <- as.data.frame(obj@Seurat$Sig.PCs.Data[, 1:2])
scrna_pca_df <- as.data.frame(obj@Scrna$Sig.PCs.Data[, 1:2])

# Run PCA
p.pca <- ggplot(seurat_pca_df) + geom_point(aes(PC_1, PC_2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Seurat PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))
p.pca.scrna <- ggplot(scrna_pca_df) + geom_point(aes(PC1, PC2))  +
                                        xlab("PC1") + ylab("PC2") +  ggtitle(paste("Scrna PCA")) + theme_grey() +
                                          theme(plot.title = element_text(hjust = 0.5))

# Plot the Tsne
seurat.tsne <- as.data.frame(obj@Seurat$Tsne.Data)
p.seurat.tsne <-  ggplot(seurat.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.tsne <- as.data.frame(obj@Scrna$Tsne.Data)
p.scrna.tsne <-  ggplot(scrna.tsne) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Tsne"), x = "Tsne_1", y = "Tsne_2") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot UMAP
seurat.umap <- as.data.frame(obj@Seurat$Umap.Data)
p.seurat.umap <- ggplot(seurat.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Seurat Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

scrna.umap <- as.data.frame(obj@Scrna$Umap.Data)
p.scrna.umap <- ggplot(scrna.umap) + geom_point(aes(V1, V2)) + labs(title = paste("Scrna Umap"), x = "UMAP_1", y = "UMAP_1") + theme_gray() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))


# combine the plots
plots <- plot_grid(p.pca, p.pca.scrna, p.seurat.tsne, p.scrna.tsne, 
                       p.seurat.umap, p.scrna.umap,
                   heatmap, labels = c("A", "B","C", "D", "E", "F","G", "H"))

gc()
counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sce <- sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F)

gc()
res.deng.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.deng.clustering <- t(as.data.frame(res.deng.clustering))
colnames(res.deng.clustering) <- c("deng")

res.deng.clustering <- as.data.frame(res.deng.clustering)
res.deng.clustering <- setDT(res.deng.clustering, keep.rownames = T)[]
colnames(res.deng.clustering) <- c("Method", "AdjustedRandIndex")
p.deng.bar <- res.deng.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor" , T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Deng et al Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

# Tasic Reads
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Brain/tasic-reads.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
tasic.counts <- counts(sce)

p.tasic.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("tasic et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

gc()
counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sce <- sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F)

gc()
res.tasic.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.tasic.clustering <- t(as.data.frame(res.tasic.clustering))
colnames(res.tasic.clustering) <- c("Tasic")

res.tasic.clustering <- as.data.frame(res.tasic.clustering)
res.tasic.clustering <- setDT(res.tasic.clustering, keep.rownames = T)[]
colnames(res.tasic.clustering) <- c("Method", "AdjustedRandIndex")
p.tasic.bar <- res.tasic.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor" , T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Tasic et al Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

