---
title: "Covariance  Analysis"
author: "Elijah Willie"
date: "26/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(aricode)
  library(Matrix)
  library(Rcpp)
  library(DuoClustering2018)
  library(ggrepel)
  library(pcurve)
  library(fpc)
  # library(Rfast)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
source("Kernel_Functions.R")
source("run_CIDR.R")
source("~/Documents/Spectrum/R/core_functions.R")
source("~/Documents/Spectrum/R/kernel_functions.R")
source("~/Documents/Spectrum/R/plotting_functions.R")
source("~/Documents/Spectrum/R/spectrum.R")
source("run_Ascend.R")
source("run_CIDR.R")
source("run_Monocle.R")
source("run_pcaReduce.R")
# source("run_RaceID3.R")
source("run_Sincell.R")
source("run_sscClust.R")
source("run_TSCAN.R")
source("run_SC3.R")
  source("run_Seurat.R")
source("run_SIMLR.R")
source("r_autoencoder.R")
source("multiple_kernel.R")
source("Cor_BLAS.R")
source("FindMarkers.R")
source("Simulation_Setup.R")
source("cpca_mod.R")
source("stepwisecpc.R")
source("clusterlab.R")
# source("UnPac_Mod.R")
# source("Silverman_Mod.R")
library(splatter)
# source_python("Modality_Python.py")
# source_python("knn_density_test.py")
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")

# source_python("~/Documents/Clusterability/VASC/codes/vasc.py")
```


# Gold Standard
```{r}
load("../Datasets/Sce_CellRanger.RData")
meta.data <- colData(sce)
trueLabels <- as.factor(meta.data$Truth)
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Gold Standard PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce), sparse = TRUE)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")



# p.pca.dip <- PlotPcDensity(obj)
# p.pca.silver <- PlotPcDensity(obj, test = "Silver")
# p.pcurve.dip <- PlotPcurveDensity(obj)
# p.pcurve.silver <- PlotPcurveDensity(obj, test = "Silver")
# 
# # 
# Log <- as.data.frame(unlist(obj@Tests$Seurat))
# NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform))
# Multinom <- as.data.frame(unlist(obj@Tests$Scrna))  
# 
# res.modality <- cbind(Log, Multinom, NegBinom)
# colnames(res.modality) <- c("Log", "Multinom", "NegBinom")
# 
# res.modality <- data.table::setDT(res.modality, keep.rownames = TRUE)
# res.modality.melted <- data.table::melt(res.modality, id.vars = "rn", variable.name = "Model")
# res.modality.melted$value[res.modality.melted$value == 0] <- 2.2e-16
# res.modality.melted$value <- round(-log(res.modality.melted$value), 2)
# 
# p1 <- ggplot2::ggplot(res.modality.melted, aes(as.factor(rn), value, color = Model)) + geom_point() +  xlab("Test") + ylab("-Log(pval)") + theme_gray() + geom_label_repel(aes(label = value),
#                     size = 5) + geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "red", size=0.5)  +  
#   ggtitle("Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14))
# 
#  p.ari <- res.modality.melted %>% 
#     ggplot(aes(factor(rn), value)) + geom_bar(stat="identity", aes(fill=Model), position=position_dodge()) + labs(title = "Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14), axis.text.x = element_text(angle = 90)) + xlab("Test") + ylab("-Log(pval)") +
#    geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "black", size=0.5) +  scale_fill_npg()


obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
# res <- RunMethods(obj)
# p.final <- GeneratePlots(obj = res$obj, res.table = res$table, pca = p.pca, k = length(unique(trueLabels)), name = "Freytag et al Gold", res.dip = res.dip)
```

```{r}
data <- as.matrix(obj@Seurat$Sig.PCs.Data)
pointwise_test(data)
sys = import('sys')
x <- sys$stdout$flush()
```



# Silver 1
```{r, echo=FALSE}
# load in the dataset
load("../Datasets/Sce_Dataset1.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Freytag et al Silver 1 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")
data.frame(unlist(obj@Tests))
# 
# Log <- as.data.frame(unlist(obj@Tests$Seurat))
# NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform))
# Multinom <- as.data.frame(unlist(obj@Tests$Scrna))
# 
# res.modality <- cbind(Log, Multinom, NegBinom)
# colnames(res.modality) <- c("Log", "Multinom", "NegBinom")
# 
# res.modality <- data.table::setDT(res.modality, keep.rownames = TRUE)
# res.modality.melted <- data.table::melt(res.modality, id.vars = "rn", variable.name = "Model")
# res.modality.melted$value[res.modality.melted$value == 0] <- 2.2e-16
# res.modality.melted$value <- round(-log(res.modality.melted$value), 2)
# 
# p1 <- ggplot2::ggplot(res.modality.melted, aes(as.factor(rn), value, color = Model)) + geom_point() +  xlab("Test") + ylab("-Log(pval)") + theme_gray() + geom_label_repel(aes(label = value),
#                     size = 5) + geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "red", size=0.5)  +  
#   ggtitle("Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14))
# 
#  p.ari <- res.modality.melted %>% 
#     ggplot(aes(factor(rn), value)) + geom_bar(stat="identity", aes(fill=Model), position=position_dodge()) + labs(title = "Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14), axis.text.x = element_text(angle = 90)) + xlab("Test") + ylab("-Log(pval)") +
#    geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "black", size=0.5) +  scale_fill_npg()

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")


obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)

```

# Silver 2
```{r}
# load in the dataset
load("../Datasets/Sce_Dataset2.RData")
# sce <- readRDS("../Data/Hard_Datasets/chen.rds")
# load("../Data/Hard_Datasets/muraro.rds")
meta.data <- colData(sce)
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Manno et al Human PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

trueLabels <- as.numeric(as.factor(meta.data$Truth))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")
data.frame(unlist(obj@Tests))

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```  


# Segerstolpe
```{r}
sce <- readRDS("../Data/Hard_Datasets/segerstolpe.rds")
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Segerstolpe et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot 
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")
data.frame(unlist(obj@Tests))

# # 
# Log <- as.data.frame(unlist(obj@Tests$Seurat))
# NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform))
# Multinom <- as.data.frame(unlist(obj@Tests$Scrna))
# 
# res.modality <- cbind(Log, Multinom, NegBinom)
# colnames(res.modality) <- c("Log", "Multinom", "NegBinom")
# 
# res.modality <- data.table::setDT(res.modality, keep.rownames = TRUE)
# res.modality.melted <- data.table::melt(res.modality, id.vars = "rn", variable.name = "Model")
# res.modality.melted$value[res.modality.melted$value == 0] <- 2.2e-16
# res.modality.melted$value <- round(-log(res.modality.melted$value), 2)
# 
# p1 <- ggplot2::ggplot(res.modality.melted, aes(as.factor(rn), value, color = Model)) + geom_point() +  xlab("Test") + ylab("-Log(pval)") + theme_gray() + geom_label_repel(aes(label = value),
#                     size = 5) + geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "red", size=0.5)  +  
#   ggtitle("Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14))
# 
#  p.ari <- res.modality.melted %>% 
#     ggplot(aes(factor(rn), value)) + geom_bar(stat="identity", aes(fill=Model), position=position_dodge()) + labs(title = "Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14), axis.text.x = element_text(angle = 90)) + xlab("Test") + ylab("-Log(pval)") +
#    geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "black", size=0.5) +  scale_fill_npg()

# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```


# Baron Mouse
```{r}
sce <- readRDS("../Data/Hard_Datasets/baron-mouse.rds")

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Baron et al Mouse PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)
# obj <- PreprocessObject(obj, method = "Randomly", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")
data.frame(unlist(obj@Tests))

# # 
# Log <- as.data.frame(unlist(obj@Tests$Seurat))
# NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform))
# Multinom <- as.data.frame(unlist(obj@Tests$Scrna))
# 
# res.modality <- cbind(Log, Multinom, NegBinom)
# colnames(res.modality) <- c("Log", "Multinom", "NegBinom")
# 
# res.modality <- data.table::setDT(res.modality, keep.rownames = TRUE)
# res.modality.melted <- data.table::melt(res.modality, id.vars = "rn", variable.name = "Model")
# res.modality.melted$value[res.modality.melted$value == 0] <- 2.2e-16
# res.modality.melted$value <- round(-log(res.modality.melted$value), 2)
# 
# p1 <- ggplot2::ggplot(res.modality.melted, aes(as.factor(rn), value, color = Model)) + geom_point() +  xlab("Test") + ylab("-Log(pval)") + theme_gray() + geom_label_repel(aes(label = value),
#                     size = 5) + geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "red", size=0.5)  +  
#   ggtitle("Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14))
# 
#  p.ari <- res.modality.melted %>% 
#     ggplot(aes(factor(rn), value)) + geom_bar(stat="identity", aes(fill=Model), position=position_dodge()) + labs(title = "Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14), axis.text.x = element_text(angle = 90)) + xlab("Test") + ylab("-Log(pval)") +
#    geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "black", size=0.5) +  scale_fill_npg()

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```


# Marques
```{r}
sce <- readRDS("../Data/Hard_Datasets/marques.rds")

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Marques et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

# 


obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```


# Klien
```{r}
sce <- readRDS("../Data/Hard_Datasets/klein.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Klein et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")


obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```


# Chen
```{r}
sce <- readRDS("../Data/Hard_Datasets/chen.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Klein et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")


# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```

# Zheng
```{r}
sce <- sce_full_Zhengmix4eq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")



obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```

# Zheng8uneq
```{r}
sce <- sce_full_Zhengmix8eq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng Mix 8 Unequal PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")



obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```

Kumar Hard
```{r}
sce <- sce_full_SimKumar8hard()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Kumar et al sim hard PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")



obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")
# 
# t <- meta.data[colnames(obj@Data$cleaned), ]
# trueLabels <- t$cell_type2

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```


HMS
```{r}
counts_new <- fread("../Data/HMSFsp_raw_data.txt", nThread = 11) %>% column_to_rownames(var = "GENE")
meta.data <- fread("../Data/HMSFsp_raw_metadata.txt")
meta.data <- meta.data[-1, ]

meta.data <- column_to_rownames(meta.data, var = "NAME")
trueLabels <- meta.data$lineage

tsne.groups <- fread("../Data/HMSFsp_raw_tsne_groupings.txt")
tsne.groups <- tsne.groups[-1, ]
Lineage <- tsne.groups$lineage

# plot the true groupings
p.tsne <- ggplot(tsne.groups) + geom_point(aes(x = as.numeric(tsne.groups$X), y = as.numeric(tsne.groups$Y), color = Lineage)) +
  labs(title = "HMS True Clusters", x = "Tsne_1", y = "Tsne_2") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

counts_new <- counts_new[, rownames(meta.data)]
obj <- CreateModalityObject(as.matrix(counts_new))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
gc()
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
gc()
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)
gc()

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

# compute transformations

obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")


# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

trueLabels <- meta.data[colnames(obj@Seurat$Scaled.Data), ]
seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble.labs <- diceR::LCA(ensemble.mat)
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)

# visualize the enseble
# evecs <- as.data.frame(obj@Scrna$Tsne.Data)
# colnames(evecs) <- c("tSNE_1", "tSNE_2")
# Multiview.Clusters <- as.factor(obj@Labels$All)
# p.multiview<- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Multiview.Clusters)) + 
#   labs(title = paste("Chen et al Multiview Clusters, ARI = 0.50")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# Ensemble.Clusters <- as.factor(ensemble.labs)
# p.ensemble <- ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Ensemble.Clusters)) + 
#   labs(title = paste("Chen et al Ensemble Clusters, ARI = 0.63")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# Seurat.Clusters <- as.factor(res.seurat$clusters)
# p.seurat <-  ggplot(evecs) + geom_point(aes(x = tSNE_1, y = tSNE_2, color = Seurat.Clusters)) + 
#   labs(title = paste("Chen et al Seurat Clusters, ARI = 0.36")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main = paste("Chen et al Dip heatmap"),
#                                   display_numbers = T, number_color = "black", fontsize_number = 20)
# p.dip <- ggplotify::as.ggplot(obj.heatmap)
# 
# p.final <- plot_grid(p.tsne, p.dip, p.multiview, p.ensemble, p.seurat, labels = c("A", "B", "C", "D", "E"))
```

# Zeisel
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Brain/zeisel.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
zeisel.counts <- counts(sce)

p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Zeisel et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(zeisel.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

# compute transformations
obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

# run modality test
# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)

ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble.labs <- diceR::LCA(ensemble.mat)
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)
```

# Baron Human
```{r}
sce <- readRDS("../Data/Hard_Datasets/baron-human.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Baron et al Human PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")


obj <- ComputeTransformations(obj)
obj <- ComputeTransformations(obj, method = "Scrna")
obj <- ComputeTransformations(obj, method = "SCTransform")
obj <- ComputeTransformations(obj, method = "All")

obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)
#
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)

Ensemble.Clusters <- as.factor(ensemble.labs)
Multiview.Clusters <- as.factor(obj@Labels$All)

# evecs <- as.data.frame(obj@Scrna$Tsne.Data)
# p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Ensemble.Clusters)) + 
#     labs(title = paste("Fretag et al Gold Standard Ensemble Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# p.multiview <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Multiview.Clusters)) + 
#     labs(title = paste("Fretag et al Gold Standard  Multiview Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

```

Campbell
```{r}
sce <- readRDS("../Data/Hard_Datasets/campbell.rds")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Campbell et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))


obj <- CreateModalityObject(counts(sce))
rm(sce)
gc()
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
gc()
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
gc()
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

obj <- ComputeTransformations(obj)
gc()
obj <- ComputeTransformations(obj, method = "Scrna")
gc()
obj <- ComputeTransformations(obj, method = "SCTransform")
gc()
obj <- ComputeTransformations(obj, method = "All")



obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

t <- meta.data[colnames(obj@Data$cleaned), ]
trueLabels <- t$cell_type1
seurat.rand <- adjustedRandIndex(trueLabels, obj@Labels$Seurat)
scrna.rand <- adjustedRandIndex(trueLabels, obj@Labels$Scrna)
sct.rand <- adjustedRandIndex(trueLabels, obj@Labels$SCTransform)
all.rand <- adjustedRandIndex(trueLabels, obj@Labels$All)
#
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
ensemble.labs <- c(cl_class_ids(cons))
ensemle.rand <- adjustedRandIndex(trueLabels, ensemble.labs)

# Ensemble.Clusters <- as.factor(ensemble.labs)
# Multiview.Clusters <- as.factor(obj@Labels$All)
# 
# evecs <- as.data.frame(obj@Seurat$Umap.Data)
# p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Ensemble.Clusters)) + 
#     labs(title = paste("Campbell et al Ensemble Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# p.multiview <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Multiview.Clusters)) + 
#     labs(title = paste("Campbell et al Multiview Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

