---
title: "Data Analysis Salmonella No CC no Myeloid"
author: "Elijah Willie"
date: "March 19, 2019"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in required libraries
```{r}
setwd("/home/elijah/Documents/Clusterability")
rm(list = ls())
#library(sf)
library(Seurat)
library(fastcluster)
library(parallelDist)
library(tidyverse)
library(cluster)
library(Rclusterpp)
library(sigclust2)
library(data.table)
library(dendextend)
library(corrplot)
library(ape)
library(parallel)
library(agricolae)
library(lubridate)
library(factoextra)
library(clustertend)
library(Emcdf)
library("diptest")
library(Rtsne)
library(cluster)
#load helper functions
source("Helper_Functions.R")
#source("Consensus_Function.R")
```

# Preprocess the data
```{r}
#create the seurat object
obj <- .CreateSeuratObj("Data/Salmonella_noCC_nomyeloid.txt", Pname = "Hash no CC no Tfh", minCells = 5, minGenes = 200, matrix = F, sep = "\t")

#Preprocess the data
obj <- .PreProcess(obj, low_thres = c(200, -Inf), high_thres = c(2500, 0.05))

#compute the number of variable genes
length(obj@var.genes)
```

# Sort the highly variable by dispersion
```{r}
#get the variable genes sorted
varGenes <- .SortGenes(obj)

#get the data containing the top genes
obj_sub <- .GetGeneData(obj, varGenes$gene)

#rm(obj)
#do some garbage collection
gc()
```

# Run the first test
```{r}
result <- .run_dip(350, obj_sub, varGenes = varGenes)
#create a sequence of numbers
seq_vals <- seq(50,350, by = 50)

#iterate over sequence values and run program
results <- NULL
for(val in seq_vals){
  result <- .run_dip(val, obj_sub, varGenes = varGenes)
  #plot the result
  plot(result$plot)
  results[[val/50]] = result
  gc()
}


#remove null values from the results
results <- Filter(Negate(is.null), results)
```

# Run the second test
```{r}
boot_pvals <- NULL
dist_list <- NULL
dip_results <- NULL
seq_vals <- seq(50,350, by = 50)
for(i in seq_vals){
  print(i)
  #permute the data
  permuted <- as.matrix(obj_sub[varGenes$gene[1:i], ])
    #.GetGeneData(obj,varGenes$gene[1:i])
    #GF_sub[sample(nrow(GF_sub), , replace=TRUE),]

  #compute the distance
  data_dist <- parallelDist(t(permuted))
  dist_list[[i/50]] <- data_dist
  gc()
  #compute the dip stat
  boot_pvals[[i/50]] <- dip.test(data_dist)$p.value
  #dip_results[[i/50]] <- dip(data_dist, full.result = T)
  gc()
}
boot_pvals
```

# Run the 3rd test
```{r}
#run consensus clustering
output <- .Boot_Con(t(obj_sub), obj, distance="euclidean", method="ward",nboot=100)

#extract the dendrogram
dend <- as.dendrogram(output$dendrogram)

#plot it
plot(dend, type = "rectangle", ylab = "Height", edgePar = list(col = 2:3, lwd = 2:1))

#compute the cluster assignments
assignments <- cutree(dend, 2)

#run the significance testing 
Sig_Res <- sigclust(t(obj_sub), labels = assignments)

#print the p value
Sig_Res$p_norm
```

# Perform PCA
```{r}
genes <- obj@data@Dimnames[[1]]
#first run PCA
obj <- RunPCA(object = obj, pc.genes = obj@var.genes, do.print = TRUE, pcs.print = 1:5, 
    genes.print = 5)

#extract the first PC
pc_1 <- as.matrix(GetCellEmbeddings(object = obj, reduction.type = "pca", dims.use = 1))
```

# Perform pc significance testing
```{r}
#determine statistically significant PCs using jackstraw
obj <- JackStraw(object = obj, num.replicate = 100, display.progress = TRUE,  num.cores = 4,do.par = T)
obj <- JackStrawPlot(object = obj)

sig_pcs <- sum(obj@dr$pca@jackstraw@overall.p.values < 0.05)

# extract the significant PCs data
data_pca <- as.matrix(GetCellEmbeddings(object = obj, reduction.type = "pca", dims.use = 1:sig_pcs))

# add consensus clustering metadata
obj@meta.data$consensus.clusters <- assignments

# add significance clustering metadata
#n_sig <- sum(result$shc$p_norm < 0.05)
#obj@meta.data$significance.clustering <- cutree(result$shc$hc_dat, n_sig+1)
# Run Tsne on the data
obj <- RunTSNE(object = obj, dims.use = 1:sig_pcs, do.fast = TRUE)

#plot the initial Tsne
TSNEPlot(obj)

#plot tsne and color by significant cluster
#TSNEPlot(obj, group.by ="significance.clustering", title = "Nippo ALL Tsne")

#plot tsne and color by consensus clusters
TSNEPlot(obj, group.by ="consensus.clusters", title = "Nippo ALL Tsne")

# run the dip test on the significant PCs
```

# run the dip test on the significant PCs
```{r}
#perform the dip test on the pairwise distances between the significant PCs rotations
pca_dist <- parallelDist(data_pca)
dip_pca <- dip.test(parallelDist(data_pca))$p.value
```

```{r}
dist_full <- parallelDist(t(obj_sub[varGenes$gene[1:350], ]))
hist(dist_full, main = "SPF Density Plot", xlab = "Distance", probability = T, col = "red")
lines(density(dist_full), col="blue", lwd=2)
```
# Perform the dip test on the first principal component
```{r}
#lets get the density plot of the first pc
hist(pc_1, main = "SPF Density Plot of the first PC", xlab = "Value", probability = T, col = "red")
lines(density(pc_1), col="blue", lwd=2)

#run the dip test
dip.test(pc_1)
```

# Compute 1d cluster and plot it on tsne
```{r}
result <- Ckmeans.1d.dp(pc_1,2)

obj@meta.data$single_clusters <- result$cluster

TSNEPlot(obj, group.by ="single_clusters", title = "SPF ALL Tsne")
```