---
title: "Duo Clustering"
author: "Elijah Willie"
date: "19/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required librares
```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(Matrix)
  library(Rcpp)
  library(DuoClustering2018)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
source("run_CIDR.R")
source("run_RaceID3.R")
source("run_TSCAN.R")
source("run_Ascend.R")
source("run_Monocle.R")
source("run_pcaReduce.R")
source("run_Sincell.R")
source("run_sscClust.R")
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
```

# Zheng
```{r}
sce <- sce_full_Zhengmix4eq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 1000)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5, type = "All")

# plot result table
obj <- .PlotRes(obj, type = "All")
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = 500, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Zheng 4x uneq
```{r}
sce <- sce_full_Zhengmix4uneq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 1000)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = 500, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Zheng 8X
```{r}
sce <- sce_full_Zhengmix8eq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Kumar hard
```{r}
sce <- sce_full_SimKumar4hard()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Kumar PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
# res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

