---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(aricode)
  library(Matrix)
  library(Rcpp)
  library(DuoClustering2018)
  library(ggrepel)
  library(pcurve)
  # library(Rfast)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
source("Kernel_Functions.R")
source("run_CIDR.R")
source("~/Documents/Spectrum/R/core_functions.R")
source("~/Documents/Spectrum/R/kernel_functions.R")
source("~/Documents/Spectrum/R/plotting_functions.R")
source("~/Documents/Spectrum/R/spectrum.R")
source("run_Ascend.R")
source("run_CIDR.R")
source("run_Monocle.R")
source("run_pcaReduce.R")
# source("run_RaceID3.R")
source("run_Sincell.R")
source("run_sscClust.R")
source("run_TSCAN.R")
source("run_SC3.R")
source("run_Seurat.R")
source("run_SIMLR.R")
source("r_autoencoder.R")
source("multiple_kernel.R")
source_python("Modality_Python.py")
library(splatter)
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
```


# Load in Citro
```{r}
# get the counts data
# temp <- Read10X("../Data/Benchmarks/CD19_B_Cells/matrices_mex/hg19/")
counts <- fread("../Data/Citro_hash_noCycle_noMyeloid.txt") %>% column_to_rownames(var = "V1")

# run the pipeline
obj <- CreateModalityObject(as.matrix(counts), sparse = TRUE)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)


obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

sigVecs <- .SigPCs(as.matrix(obj@Seurat$Scaled.Data))$sigVecs
deucl <- as.vector(as.matrix(parallelDist(sigVecs)))
deucl.pval <- dip.test(deucl)$p.value
dcor <- as.vector(coop::cosine(t(sigVecs)))
dcor.pval <- dip.test(dcor)$p.value
citro.df <- data.frame(Euclidean = deucl, Cosine = dcor)
# citro.df.melted <- melt(citro.df)
# 
# colnames(citro.df.melted) <- c("Distance", "Density")


p.eucl <- ggplot(citro.df, aes(Euclidean)) + geom_density(alpha = 0.2) +
     ggtitle("Citro Significant PCs, Dip Test Pval = 0.10") + 
     theme(plot.title = element_text(hjust = 0.5, size=18), axis.title=element_text(size=18), legend.key.size = unit(1, "cm"), legend.title=element_text(size=12), legend.text=element_text(size=14))  + labs(x = "Euclidean Distance")

p.cor <- ggplot(citro.df, aes(Cosine)) + geom_density(alpha = 0.2) +
     ggtitle("Citro Significant PCs, Dip Test Pval = 1.0") + 
     theme(plot.title = element_text(hjust = 0.5, size=18), axis.title=element_text(size=18), legend.key.size = unit(1, "cm"), legend.title=element_text(size=12), legend.text=element_text(size=14))  + labs(x = "Cosine Similarity")

sigclust <- .ConsensusTest(sigVecs, retTree = T)

# plot the tree
citro.plt.tree <- .PlotRes(sigclust$Tree, datName = 'Citro')

p.citro.final <- plot_grid(p.eucl, p.cor, citro.plt.tree, labels = c("A", "B", "C"))
# run modality test
# obj <- TestModality(obj)
# obj <- TestModality(obj, type = "Scrna")
# # obj <-TestModality(obj, type = "SCTransform")
# 
# p.pca.dip <- PlotPcDensity(obj)
# p.pca.silver <- PlotPcDensity(obj, test = "Silver")
# p.pcurve.dip <- PlotPcurveDensity(obj)
# p.pcurve.silver <- PlotPcurveDensity(obj, test = "Silver")
# p.final <- plot_grid(p.pca.dip, p.pca.silver, labels = c("A", "B"))
# p.final.silver <- plot_grid(p.pcurve.dip, p.pcurve.silver, labels = c("A", "B"))

# 
# Log <- as.data.frame(unlist(obj@Tests$Seurat))
# NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform))
# Multinom <- as.data.frame(unlist(obj@Tests$Scrna))
# 
# res.modality <- cbind(Log, Multinom, NegBinom)
# colnames(res.modality) <- c("Log", "Multinom", "NegBinom")
# 
# res.modality <- data.table::setDT(res.modality, keep.rownames = TRUE)
# res.modality.melted <- data.table::melt(res.modality, id.vars = "rn", variable.name = "Model")
# res.modality.melted$value[res.modality.melted$value == 0] <- 2.2e-16
# res.modality.melted$value <- round(-log(res.modality.melted$value), 2)
# 
# p1 <- ggplot2::ggplot(res.modality.melted, aes(as.factor(rn), value, color = Model)) + geom_point() +  xlab("Test") + ylab("-Log(pval)") + theme_gray() + geom_label_repel(aes(label = value),
#                     size = 5) + geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "red", size=0.5)  +  
#   ggtitle("Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14))
# 
#  p.2 <- res.modality.melted %>% 
#     ggplot(aes(factor(rn), value)) + geom_bar(stat="identity", aes(fill=Model), position=position_dodge()) + labs(title = "Modality Testing Results") + theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14), axis.text.x = element_text(angle = 90)) + xlab("Test") + ylab("-Log(pval)") +
#    geom_hline(yintercept=-log(0.05), linetype="dashed", 
#                 color = "black", size=0.5) +  scale_fill_npg()
 
# obj <- ComputeTransformations(obj)
# obj <- ComputeTransformations(obj, method = "Scrna")
# obj <- ComputeTransformations(obj, method = "SCTransform")
# obj <- ComputeTransformations(obj, method = "All")
# 
# 
# obj <- .RunConsensus(obj)
# obj <- .RunConsensus(obj, method = "Scrna")
# obj <- .RunConsensus(obj, method = "SCTransform")
# obj <- .RunConsensus(obj, method = "All")
# 
# ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
# ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
# cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
# ensemble.labs <- c(cl_class_ids(cons))
# 
# obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="Citro Hash Dip Heatmap",
#                                     display_numbers = T, number_color = "black")
# p.dip <- ggplotify::as.ggplot(obj.heatmap)
# 
# Clusters <- as.factor(ensemble.labs)
# evecs <- as.data.frame(obj@Scrna$Umap.Data)
# p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
#     labs(title = paste("Citro Hash Ensemble Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# p.final <- plot_grid(p.dip, p.evecs, labels = c("A", "B"))
```


# Salmonella
```{r}
# get the counts data
counts <- fread("../Data/Salmonella_hash_noCycle_noMyeloid.txt") %>% column_to_rownames(var = "V1")

obj <- CreateModalityObject(as.matrix(counts), sparse = TRUE)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

sigVecs <- .SigPCs(as.matrix(obj@Seurat$Scaled.Data))$sigVecs
deucl <- as.vector(as.matrix(parallelDist(sigVecs)))
deucl.pval <- dip.test(deucl)$p.value
dcor <- as.vector(coop::cosine(t(sigVecs)))
dcor.pval <- dip.test(dcor)$p.value
sal.df <- data.frame(Euclidean = deucl, Correlation = dcor)


p.eucl <- ggplot(sal.df, aes(Euclidean)) + geom_density(alpha = 0.2) +
     ggtitle("Salmonella Significant PCs, Dip Test Pval = 0.10") + 
     theme(plot.title = element_text(hjust = 0.5, size=18), axis.title=element_text(size=18), legend.key.size = unit(1, "cm"), legend.title=element_text(size=12), legend.text=element_text(size=14))  + labs(x = "Euclidean Distance")

p.cor <- ggplot(sal.df, aes(Correlation)) + geom_density(alpha = 0.2) +
     ggtitle("Salmonella Significant PCs, Dip Test Pval = 0.10") + 
     theme(plot.title = element_text(hjust = 0.5, size=18), axis.title=element_text(size=18), legend.key.size = unit(1, "cm"), legend.title=element_text(size=12), legend.text=element_text(size=14))  + labs(x = "Cosine Similarity")

sigclust <- .ConsensusTest(sigVecs, retTree = T)

# plot the tree
sal.plt.tree <- .PlotRes(sigclust$Tree, datName = 'Salmonella')

p.sal.final <- plot_grid(p.eucl, p.cor, sal.plt.tree, labels = c("A", "B", "C"))

# add the scrna slot
# obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# obj <- PreprocessObject(obj, method = "SCTransform", nFeatures = 500)


# Run the modality tests
# obj <- TestModality(obj)
# obj <- TestModality(obj, type = "Scrna")
# obj <-TestModality(obj, type = "SCTransform")
# 
# p.pca.dip <- PlotPcDensity(obj)
# p.pca.silver <- PlotPcDensity(obj, test = "Silver")
# p.pcurve.dip <- PlotPcurveDensity(obj)
# p.pcurve.silver <- PlotPcurveDensity(obj, test = "Silver")
# p.final <- plot_grid(p.pca.dip, p.pca.silver, labels = c("A", "B"))
# p.final.curve <- plot_grid(p.pcurve.dip, p.pcurve.silver, labels = c("A", "B"))
# 
# 
# obj <- ComputeTransformations(obj)
# obj <- ComputeTransformations(obj, method = "Scrna")
# obj <- ComputeTransformations(obj, method = "SCTransform")
# obj <- ComputeTransformations(obj, method = "All")
# 
# 
# obj <- .RunConsensus(obj)
# obj <- .RunConsensus(obj, method = "Scrna")
# obj <- .RunConsensus(obj, method = "SCTransform")
# obj <- .RunConsensus(obj, method = "All")
# # obj <- .RunConsensus(obj, method = "All")
# 
# ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
# ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
# cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
# ensemble.labs <- c(cl_class_ids(cons))
# 
# obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="Salmonella Dip Heatmap",
#                                     display_numbers = T, number_color = "black")
# p.dip <- ggplotify::as.ggplot(obj.heatmap)
# 
# Clusters <- as.factor(ensemble.labs)
# evecs <- as.data.frame(obj@Scrna$Umap.Data)
# p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
#     labs(title = paste("Salmonella Ensemble Clusters")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# p.final <- plot_grid(p.dip, p.evecs, labels = c("A", "B"))
```



```{r}
# get the counts data
counts <- fread("../Data/SPF_allTcells.txt") %>% column_to_rownames(var = "V1")

obj <- CreateModalityObject(as.matrix(counts), sparse = TRUE)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

sigVecs <- .SigPCs(as.matrix(obj@Seurat$Scaled.Data))$sigVecs
deucl <- as.vector(as.matrix(parallelDist(sigVecs)))
deucl.pval <- dip.test(deucl)$p.value
dcor <- as.vector(coop::cosine(t(sigVecs)))
dcor.pval <- dip.test(dcor)$p.value
sal.df <- data.frame(Euclidean = deucl, Cosine = dcor)


p.eucl <- ggplot(sal.df, aes(Euclidean)) + geom_density(alpha = 0.2) +
     ggtitle("SPF Significant PCs, Dip Test Pval = 0.0") + 
     theme(plot.title = element_text(hjust = 0.5, size=18), axis.title=element_text(size=18), legend.key.size = unit(1, "cm"), legend.title=element_text(size=12), legend.text=element_text(size=14))  + labs(x = "Euclidean Distance")

p.cor <- ggplot(sal.df, aes(Cosine)) + geom_density(alpha = 0.2) +
     ggtitle("SPF Significant PCs, Dip Test Pval = 0.0") + 
     theme(plot.title = element_text(hjust = 0.5, size=18), axis.title=element_text(size=18), legend.key.size = unit(1, "cm"), legend.title=element_text(size=12), legend.text=element_text(size=14))  + labs(x = "Cosine Similarity")

sigclust <- .ConsensusTest(sigVecs, retTree = T)

# plot the tree
spf.plt.tree <- .PlotRes(sigclust$Tree, datName = 'SPF')

p.spf.final <- plot_grid(p.eucl, p.cor, spf.plt.tree, labels = c("A", "B", "C"))

# run the pipeline
# obj <- CreateModalityObject(as.matrix(counts))
# 
# # add the seurat slot
# obj <- PreprocessObject(obj,  nFeatures = 500)
# 
# # add the scrna slot
# obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)
# 
# obj <- PreprocessObject(obj, method = "SCTransform", nFeatures = 500)


# Run the modality tests
# obj <- TestModality(obj)
# obj <- TestModality(obj, type = "Scrna")
# obj <-TestModality(obj, type = "SCTransform")
# 
# p.pca.dip <- PlotPcDensity(obj)
# p.pca.silver <- PlotPcDensity(obj, test = "Silver")
# p.pcurve.dip <- PlotPcurveDensity(obj)
# p.pcurve.silver <- PlotPcurveDensity(obj, test = "Silver")
# p.final <- plot_grid(p.pca.dip, p.pca.silver, labels = c("A", "B"))
# p.final.curve <- plot_grid(p.pcurve.dip, p.pcurve.silver, labels = c("A", "B"))
# 
# obj <- ComputeTransformations(obj)
# obj <- ComputeTransformations(obj, method = "Scrna")
# obj <- ComputeTransformations(obj, method = "SCTransform")
# obj <- ComputeTransformations(obj, method = "All")
# 
# 
# obj <- .RunConsensus(obj)
# obj <- .RunConsensus(obj, method = "Scrna")
# obj <- .RunConsensus(obj, method = "SCTransform")
# obj <- .RunConsensus(obj, method = "All")
# # obj <- .RunConsensus(obj, method = "All")
# 
# ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform)
# ensemble <- apply(ensemble.mat, MARGIN = 2, as.cl_partition)
# cons <- cl_consensus(as.cl_ensemble(ensemble), method = "SE", control = list(nruns = 50))
# ensemble.labs <- c(cl_class_ids(cons))
# 
# obj.heatmap <- pheatmap::pheatmap(as.matrix(res.dip), cluster_rows = F, cluster_cols = F, main ="SPF All Tcells Dip Heatmap",
#                                     display_numbers = T, number_color = "black")
# p.dip <- ggplotify::as.ggplot(obj.heatmap)
# 
# Clusters <- as.factor(obj@Labels$All)
# evecs <- as.data.frame(obj@Seurat$Umap.Data)
# p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
#     labs(title = paste("SPF All Tcells Ensemble Clusters, alpha = 0.05")) + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# 
# p.final <- plot_grid(p.dip, p.evecs, labels = c("A", "B"))
```

# write plots to pddf
```{r}
pdf("../plots/Paper/Evgeny_Data_Plots_Corrected.pdf", width = 20, height = 12)
plot(p.citro.final)
plot(p.sal.final)
plot(p.spf.final)
dev.off()
```

