---
title: "Freytag Clustering"
author: "Elijah Willie"
date: "9/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(Matrix)
  library(Rcpp)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
```

# Gold standard
```{r}
load("../Datasets/Sce_CellRanger.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))

sce <- scater::normalize(sce)
p.gold.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Gold Standard PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
# res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = ceiling(ncol(obj@Data$cleaned)/2), n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.gold.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))

```


# Silver 1
```{r}
# load in the dataset
load("../Datasets/Sce_Dataset1.RData")
meta.data <- colData(sce)


sce <- scater::normalize(sce)
p.silver1.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver-1 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# silver.counts <- counts(sce)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
trueLabels <- as.numeric(as.factor(meta.data$Truth))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = ceiling(ncol(obj@Data$cleaned)/2), n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# p.final <- plot_grid(p.gold.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Silver 2
```{r}
# load in the dataset
load("../Datasets/Sce_Dataset2.RData")
meta.data <- colData(sce)


sce <- scater::normalize(sce)
p.silver2.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver-2 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

trueLabels <- as.numeric(as.factor(meta.data$Truth))

silver.counts <- counts(sce)

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = ceiling(ncol(obj@Data$cleaned)/2), n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.gold.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Silver 3
```{r}
# load in the dataset
load("../Datasets/Sce_Dataset3.RData")
meta.data <- colData(sce)


sce <- scater::normalize(sce)
p.silver3.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver-3 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

silver.counts <- counts(sce)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
trueLabels <- as.numeric(as.factor(meta.data$Truth))
# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = ceiling(ncol(obj@Data$cleaned)/2), n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```


# Silver 4
```{r}
# load in the dataset
sce  <- readRDS("../Data/Hard_Datasets/Sce_Dataset4.rds")
meta.data <- colData(sce)


sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver-4 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
trueLabels <- as.numeric(as.factor(meta.data$Truth))
# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = ceiling(ncol(obj@Data$cleaned)/2), n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Tests$Multiview$Umap$evecs)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
```

# Silver 5
```{r}
# load in the dataset
sce  <- readRDS("../Data//Hard_Datasets/Sce_Dataset5.rds")
meta.data <- colData(sce)


sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver-5 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
trueLabels <- as.numeric(as.factor(meta.data$Truth))
# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# counts.sampled <- silver.counts[, sample(ncol(silver.counts), 1500)]
# sampled.indices <- match(colnames(counts.sampled), mTeta.data@rownames)
# trueLabels <- as.numeric(as.factor(meta.data$Truth[sampled.indices]))
# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = T, svm_num_cells = ceiling(ncol(obj@Data$cleaned)/2), n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Tests$Multiview$Umap$evecs)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Zeisel
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Brain/zeisel.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
zeisel.counts <- counts(sce)

p.zeisel.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Chen et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(zeisel.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "SCTransform")
obj <- TestModality(obj, type = "Scrna")

seurat <- as.data.frame(unlist(obj@Tests$Seurat))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform))
colnames(sctransfrom) <- c("SCTransform.Dip.")

scrna <- as.data.frame(unlist(obj@Tests$Scrna))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Heatmap"), display_numbers = T, number_color = "white")
heatmap <- ggplotify::as.ggplot(obj.heatmap)

plots.zeisel <- plot_grid(p.zeisel.pca,
                   heatmap, labels = c("A", "B"))

gc()
counts.new <- obj@Data$cleaned
sce <- SingleCellExperiment(
  
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

sce <- SC3::sc3(sce, ks = length(unique(trueLabels)), biology = F, gene_filter = F, svm_num_cells = 500)

gc()
res.zeisel.clustering <- .ClusterDat(obj, sce, length(unique(trueLabels)), trueLabels)
res.zeisel.clustering <- t(as.data.frame(res.zeisel.clustering))
colnames(res.zeisel.clustering) <- c("Zeisel")

res.zeisel.clustering <- as.data.frame(res.zeisel.clustering)
res.zeisel.clustering <- setDT(res.zeisel.clustering, keep.rownames = T)[]
colnames(res.zeisel.clustering) <- c("Method", "AdjustedRandIndex")
p.zeisel.bar <- res.zeisel.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor" , T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "Zeisel et al Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

plots.zeisel.clust <- plot_grid(p.zeisel.pca, p.zeisel.bar, labels = c("A", "B"))
```

# PBMC 3k
```{r}
pbmc <- readRDS(file = "../Data/Benchmarks/pbmc3k_final.rds")

p.pbmc.umap <- DimPlot(pbmc, reduction = "umap") + ggtitle("PBMC Clusters")  + 
                                                                    theme_grey() +  theme(plot.title = element_text(hjust = 0.5))


pbmc.counts <- as.matrix(GetAssayData(pbmc, slot = "counts"))
meta.data <- as.data.frame(Idents(pbmc))
# counts.sampled <- pbmc.counts[, sample(ncol(pbmc.counts), 2500)]
# sampled.indices <- match(colnames(counts.sampled), rownames(meta.data))
trueLabels <- as.numeric(as.factor(meta.data$`Idents(pbmc)`))

# run it through the pipeline
# add the seurat slot
obj <- CreateModalityObject(pbmc.counts)
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <- TestModality(obj, type = "SCTransform")

# compute a result table for all the tests
seurat <- as.data.frame(unlist(obj@Tests$Seurat))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform))
colnames(sctransfrom) <- c("SCTransform.Dip.")

scrna <- as.data.frame(unlist(obj@Tests$Scrna))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")


# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Heatmap"), display_numbers = T, number_color = "white")
heatmap <- ggplotify::as.ggplot(obj.heatmap)

plots.3k <- plot_grid(p.pbmc.umap, heatmap, labels = c("A", "B"))

gc()
# counts.new <- obj@Data$cleaned[rownames(obj@Seurat$Scaled.Data), ]
counts.new <- obj@Data$cleaned
sce <- SingleCellExperiment(
    assays = list(counts = counts.new
                  )
)
sce <- scater::normalize(sce)
rowData(sce)$feature_symbol <- rownames(sce)
sc3_k <- sc3_estimate_k(sce)@metadata$sc3$k_estimation
sce <- SC3::sc3(sce, ks = sc3_k, biology = F, gene_filter = T, svm_num_cells = 1000)

gc()
res.pbmc.clustering <- .ClusterDat(obj, sce, sc3_num_clust = sc3_k, trueLabels)
res.pbmc.clustering <- t(as.data.frame(res.pbmc.clustering))
colnames(res.pbmc.clustering) <- c("PBMC")

res.pbmc.clustering <- as.data.frame(res.pbmc.clustering)
res.pbmc.clustering <- setDT(res.pbmc.clustering, keep.rownames = T)[]
colnames(res.pbmc.clustering) <- c("Method", "AdjustedRandIndex")
p.pbmc.bar <- res.pbmc.clustering %>% 
  dplyr::mutate(Multiview = ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Hclust.Cor", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "PBMC 3K Barplots") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

plots.3k.clust <- plot_grid(p.pbmc.umap, p.pbmc.bar, labels = c("A", "B"))
```
