---
title: "Hard Datasets"
author: "Elijah Willie"
date: "03/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(Matrix)
  library(Rcpp)
  library(DuoClustering2018)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
source("run_CIDR.R")
source("run_RaceID3.R")
source("run_TSCAN.R")
source("run_Ascend.R")
source("run_Monocle.R")
source("run_pcaReduce.R")
source("run_Sincell.R")
source("run_sscClust.R")
source("Seurat_Mod.R")
source("Ascend_Mod.R")
source("SC3_Mod.R")
source("~/Documents/Spectrum/R/core_functions.R")
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
```

# segerstolpe
```{r}
sce <- readRDS("../Data/Hard_Datasets/segerstolpe.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Segerstolpe et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))

```

# Manno Human
```{r}
sce <- readRDS("../Data/Hard_Datasets/manno_human.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Manno et al Human PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Baron Mouse
```{r}
sce <- readRDS("../Data/Hard_Datasets/baron-mouse.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Baron et al Mouse PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Marques
```{r}
sce <- readRDS("../Data/Hard_Datasets/marques.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Marques et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 1000)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Manno Mouse
```{r}
sce <- readRDS("../Data/Hard_Datasets/manno_mouse.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Manno Mouse et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 1000)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Klien
```{r}
sce <- readRDS("../Data/Hard_Datasets/klein.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Klein et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Zeisel
```{r}
sce <- readRDS("../Data/Benchmarks/Mouse/Brain/zeisel.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))
zeisel.counts <- counts(sce)

p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Zeisel et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(zeisel.counts)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

Zheng4x
```{r}
sce <- sce_full_Zhengmix4eq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng Mix 4Eq PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# compute Distances
obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


Zheng8X
```{r}
sce <- sce_full_Zhengmix8eq()
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$phenoid))

p.pca <- scater::plotPCA(sce, colour_by = "phenoid") + theme_grey() + ggtitle("Zheng Mix 8Eq PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# compute Distances
obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")

k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Gold Standard
```{r}
load("../Datasets/Sce_CellRanger.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Gold Standard PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# compute Distances
obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = obj@Scrna$Deviances, logcounts = obj@Scrna$Deviances
                  )
)
# sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, gene_filter = F, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Silver 1
```{r}
load("../Datasets/Sce_Dataset1.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver 1 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# compute Distances
obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# Silver 2
```{r}
load("../Datasets/Sce_Dataset2.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver 2 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# compute Distances
obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Silver 3
```{r}
load("../Datasets/Sce_Dataset3.RData")
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Truth))
sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "Truth") + theme_grey() + ggtitle("Fretag et al Silver 3 PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# compute Distances
obj <- ComputeDistances(obj)
obj <- ComputeDistances(obj, method = "Scrna")
obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- .estkTW(obj@Seurat$Scaled.Data)
k.scrna <- .estkTW(obj@Scrna$Deviances)
k.sct <- .estkTW(obj@SCTransform$Scaled.Data)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat, sigma = 1)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna, sigma = 1)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct, sigma = 1)
obj <- ComputeTransformations(obj, method = "All", ncomp = max(k.seurat,k.scrna,k.sct), sigma = 1)

# compute labels
obj <- .RunConsensus(obj)
obj <- .RunConsensus(obj, method = "Scrna")
obj <- .RunConsensus(obj, method = "SCTransform")
obj <- .RunConsensus(obj, method = "All")

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig" | Method == "Ensemble.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
ensemble.mat <- cbind(obj@Labels$Seurat, obj@Labels$Scrna, obj@Labels$SCTransform, obj@Labels$All)
ensemble.labs <- diceR::LCA(ensemble.mat)
Clusters <- as.factor(ensemble.labs)
evecs <- as.data.frame(obj@SCTransform$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```


# Chen
```{r}
sce <- readRDS("../Data/Hard_Datasets/chen.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Klein et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 1000)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))
```

# HMS
```{r}
counts_new <- fread("../Data/HMSFsp_raw_data.txt", nThread = 8) %>% column_to_rownames(var = "GENE")
meta.data <- fread("../Data/HMSFsp_raw_metadata.txt")
meta.data <- meta.data[-1, ]

meta.data <- column_to_rownames(meta.data, var = "NAME")
trueLabels <- meta.data$lineage

tsne.groups <- fread("../Data/HMSFsp_raw_tsne_groupings.txt")
tsne.groups <- tsne.groups[-1, ]
Lineage <- tsne.groups$lineage

# plot the true groupings
p.tsne <- ggplot(tsne.groups) + geom_point(aes(x = as.numeric(tsne.groups$X), y = as.numeric(tsne.groups$Y), color = Lineage)) +
  labs(title = "HMS True Clusters", x = "Tsne_1", y = "Tsne_2") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))
# filter the cells
counts_new <- counts_new[, rownames(meta.data)]

# run the pipeline
obj <- CreateModalityObject(as.matrix(counts_new))
gc()
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
gc()
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)
gc()
obj <- PreprocessObject(obj, method = "SCTransform", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
res.table$Seurat[[1]] <- 0.001
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.tsne, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))

```


# MD70
```{r}
# read in data matrix
counts <- readMM("../Data/MD720/gene_sorted-matrix.mtx")

feature.names = read.delim("../Data/MD720/features.tsv.gz", 
                           header = FALSE,
                           stringsAsFactors = FALSE)
barcode.names = read.delim("../Data/MD720/barcodes.tsv.gz", 
                           header = FALSE,
                           stringsAsFactors = FALSE)
colnames(counts) = barcode.names$V1
rownames(counts) = feature.names$V1

# read in metadata
tsne.cords <- fread("../Data/MD720/scp_tsne_ann.txt")
tsne.ann <- fread("../Data/MD720/scp_metadata_ann.txt")
tsne.ann <- tsne.ann[-1, ]

trueLabels <- tsne.ann$annotated_Cluster
# plot the true data
p.tsne <- ggplot(tsne.cords) + geom_point(aes(x = as.numeric(tsne.cords$X), y = as.numeric(tsne.cords$Y), color = Annotated_Clusters)) +
  labs(title = "MD70 True Clusters", x = "Tsne_1", y = "Tsne_2") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run preprocessing
obj <- CreateModalityObject(as.matrix(counts))
gc()
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
gc()
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)
gc()
obj <- PreprocessObject(obj, method = "SCTransform", nFeatures = 500)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj)
gc()
# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$Umap)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
gc()
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks = 8 , biology = F, gene_filter = T, svm_num_cells = 500, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, 8)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Multiview.Kmeans' | Method == 'Multiview.Hclust' | Method == 'Multiview.Pam' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Tests$Multiview$Umap$evecs)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.tsne, p.bar, p.evecs, labels = c("A", "B", "C"))
```

# Baron Human
```{r}
sce <- readRDS("../Data/Hard_Datasets/baron-human.rds")

meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$cell_type1))

sce <- scater::normalize(sce)
p.pca <- scater::plotPCA(sce, colour_by = "cell_type1") + theme_grey() + ggtitle("Baron Human et al PCA Plot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce))
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 1000)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 1000)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 1000)

# run modality test
obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

seurat <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
colnames(seurat) <- c("Seurat.Dip.Pvalue")

sctransfrom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
colnames(sctransfrom) <- c("SCTransform.Dip")

scrna <- as.data.frame(unlist(obj@Tests$Scrna$Dip))
colnames(scrna) <- c("Scrna.Dip.Pvalue")

res.table <- cbind(scrna, seurat, sctransfrom)
colnames(res.table) <- c("Seurat", "Scrna", "SCTransform")

# plot heat map
obj.heatmap <- pheatmap::pheatmap(as.matrix(res.table), cluster_rows = F, cluster_cols = F, main = paste("Dip Heatmap"), display_numbers = T, number_color = "black")
heatmap.dip <- ggplotify::as.ggplot(obj.heatmap)

# run consensus test
obj <- .ConsensusTest(obj, ncomp = 5)
obj <- .ConsensusTest(obj, ncomp = 5, type = "Seurat")
obj <- .ConsensusTest(obj, ncomp = 5, type = "Scrna")
obj <- .ConsensusTest(obj, ncomp = 5, type = "SCTransform")

# plot result table
obj <- .PlotRes(obj)
# get labels
obj.labels <- .MultiCutTRee(obj@Tests$Multiview$All)
seurat.labels <- .MultiCutTRee(obj@Tests$Multiview$Seurat)
scrna.lables <- .MultiCutTRee(obj@Tests$Multiview$Scrna)
sct.labels <- .MultiCutTRee(obj@Tests$Multiview$SCTransform)

# Run SC3
sce <- SingleCellExperiment(
    assays = list(counts = as.matrix(obj@Data$cleaned)
                  )
)
sce <- scater::normalize(sce)
sce <- SC3::sc3_estimate_k(sce)
sc3_num_clust <- sce@metadata$sc3$k_estimation

 # define feature names in feature_symbol column
rowData(sce)$feature_symbol <- rownames(sce)
sce <- SC3::sc3(sce, ks =sc3_num_clust , biology = F, svm_num_cells = 500, gene_filter = T, n_cores = 6)

# compute  results
res.clustering <- .ClusterDat(obj, sce, trueLabels, sc3_num_clust, All = T)
res.clustering <- t(as.data.frame(res.clustering))
colnames(res.clustering) <- c("Gold")
res.clustering <- as.data.frame(res.clustering)
res.clustering <- setDT(res.clustering, keep.rownames = T)[]
colnames(res.clustering) <- c("Method", "AdjustedRandIndex")

p.bar <- res.clustering %>% 
  dplyr::mutate(Multiview =  ifelse(Method == 'Seurat.Sig' | Method == 'Scrna.Sig' | Method == 'SCTransform.Sig' | Method == "Multiview.Sig", T, F)) %>% 
  ggplot(aes(Method, AdjustedRandIndex)) + geom_bar(stat="identity", aes(fill=Multiview)) + labs(title = "BarPlot") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

# plot the evecs and labels the clusters
Clusters <- as.factor(obj.labels)
evecs <- as.data.frame(obj@Scrna$Tsne.Data)
p.evecs <- ggplot(evecs) + geom_point(aes(x = V1, y = V2, color = Clusters)) + 
  labs(title = "Multiview Eigenvectors Clusters") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90))

p.final <- plot_grid(p.pca, p.bar, p.evecs, heatmap.dip, labels = c("A", "B", "C", "D"))

```

