---
title: "Krzak Clustering"
author: "Elijah Willie"
date: "03/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
gc()
options(warn=-1)
suppressPackageStartupMessages({
  library(Seurat)
  library(reticulate)
  library(splatter)
  library(SingleCellExperiment)
  library(ggplot2)
  library(dplyr)
  library(clue)
  library(pcaReduce)
  library(parallelDist)
  library(data.table)
  library(multiview)
  library(cowplot)
  library(diptest)
  library(pheatmap)
  library(ggplotify)
  library(tidyverse)
  library(agricolae)
  library(Matrix)
  library(Rcpp)
  library(DuoClustering2018)
  library(SIMLR)
  library(ggrepel)
  library(aricode)
  }
)
# source required functions
setwd("~/Documents/Clusterability/scripts/")
source("Helper_Functions.R")
source("~/Documents/scrna2019-master/algs/glmpca.R")
source("~/Documents/scrna2019-master/util/functions.R")
source("~/Documents/scrna2019-master/util/functions_genefilter.R")
source("Pipeline_Functions.R")
source("Clustering_Functions.R")
source("func.R")
source("Dip_Functions.R")
source("consensus_funcs.R")
source("Plot_Funcs.R")
source("cpca_mod.R")
source("cpc_eigen.R")
source("run_CIDR.R")
source("run_RaceID3.R")
source("run_TSCAN.R")
source("run_Ascend.R")
source("run_Monocle.R")
source("run_pcaReduce.R")
source("run_Sincell.R")
source("run_sscClust.R")
source("run_SC3.R")
source("run_Seurat.R")
source("run_sscClustMod.R")
source("~/Documents/Spectrum/R/core_functions.R")
# sourceCpp("test.cpp")
# source("RaceID2_StemID_class.R")
use_virtualenv("r-reticulate")
```


# Setup 1, balanced, 1000 cells, 4 groups, de prob = 0.5, dropout.mid = 0
```{r}
set.seed(1994)
batchCells=3000
nGenes=5000
# x <- runif(8)
# group.prob=x/sum(x)
group.prob <- rep(1/16, 16)
type="balanced"
de.prob=0.05
dropout.type ="experiment"
dropout.mid=0

# simulate 
params <- newSplatParams()
params <- setParams(params, batchCells=batchCells, nGenes=nGenes, 
                                            group.prob = unlist(group.prob), de.prob=de.prob, dropout.type=dropout.type, seed=1994)
sce <- splatSimulateGroups(params, verbose = TRUE)

# run through pipeline    
sce <- scater::normalize(sce)
meta.data <- colData(sce)
trueLabels <- as.numeric(as.factor(meta.data$Group))
p.pca <- plotPCA(sce, colour_by = "Group") + ggtitle(paste("Four Simulated Clusters")) + 
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90)) +  theme_grey() + 
  theme(plot.title = element_text(hjust = 0.5, size=15), axis.title=element_text(size=14))

# run it through the pipeline
obj <- CreateModalityObject(counts(sce), sparse = FALSE)
# add the seurat slot
obj <- PreprocessObject(obj,  nFeatures = 500)
# add the sctransform slot
obj <- PreprocessObject(obj,  method = "SCTransform", nFeatures = 500)
# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna", nFeatures = 500)

# obj <- ComputeDistances(obj)
# obj <- ComputeDistances(obj, method = "Scrna")
# obj <- ComputeDistances(obj, method = "SCTransform")


k.seurat <- EstimateK(obj)
k.scrna <- EstimateK(obj, method = "Scrna")
k.sct <- EstimateK(obj, method = "SCTransform")
# k.randomly <- .estkTW(obj@Randomly$Scaled.Data)
k.final <- max(k.seurat, k.scrna, k.sct)
# compute transformations

obj <- ComputeTransformations(obj, ncomp = k.seurat)
obj <- ComputeTransformations(obj, method = "Scrna", ncomp = k.scrna)
obj <- ComputeTransformations(obj, method = "SCTransform", ncomp = k.sct)
obj <- ComputeTransformations(obj, method = "All", ncomp = k.final)

obj <- TestModality(obj)
obj <- TestModality(obj, type = "Scrna")
obj <-TestModality(obj, type = "SCTransform")

Log <- as.data.frame(unlist(obj@Tests$Seurat$Dip))
NegBinom <- as.data.frame(unlist(obj@Tests$SCTransform$Dip))
Multinom <- as.data.frame(unlist(obj@Tests$Scrna$Dip))

res.dip <- cbind(Log, Multinom, NegBinom)
colnames(res.dip) <- c("Log", "Multinom", "NegBinom")
if (sum(res.dip) == 0){
  res.dip$Log[[1]] <- 0.01
}

res <- RunMethods(obj)
p.final <- GeneratePlots(obj = res$obj, res.table = res$table, pca = p.pca, k = length(unique(trueLabels)), name = "3K, DE prob = 0.05, 16 Groups", res.dip = res.dip)
```

