---
title: "Magic Analysis"
author: "Elijah Willie"
date: "22/08/2019"
output: html_document
---

# load required libraries
```{r}
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(Seurat)
  library(Seurat)
  library(parallelDist)
  library(tidyverse)
  library(Rclusterpp)
  library(data.table)
  library("diptest")
  library(Rtsne)
  library(PPCI)
  library(splatter)
  library(SC3)
  library(scater)
  library(SingleCellExperiment)
  library(jackstraw)
  library(irlba)
  library(WGCNA)
  library(Rfast)
  library(gridExtra)
  library(reticulate)
  library(corpcor)
  library(trqwe)
  library(cowplot)
  library(umap)
  library(pheatmap)
  library(ggplotify)
  library(Rmagic)
  library(phateR)
}
)
setwd("/home/elijah/Documents/Clusterability")
source("Helper_Functions.R")
source("/home/elijah/Documents/scrna2019/algs/glmpca.R")
source("/home/elijah/Documents/scrna2019/util/functions.R")
source("/home/elijah/Documents/scrna2019/util/functions_genefilter.R")
source("Pipeline_Functions.R")
use_virtualenv("r-reticulate")
use_python("/usr/local/bin/python3")
```

# Run Magic and Phate
## Citro
```{r}
# get the counts
counts <- fread("Data/Citro_hash_noCycle_noMyeloid.txt") %>% column_to_rownames(var = "V1")
obj <- CreateSeuratObject(counts, project = "Proj", min.cells = 5, min.features = 200)
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^MT-")
obj <- subset(obj, subset = nFeature_RNA > 200 & nFeature_RNA < 12000 & percent.mt < 5)
obj <- NormalizeData(object = obj, normalization.method = "LogNormalize", scale.factor = 10000, verbose = F)
obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 500, verbose = T)

counts.normalized <- as.matrix(obj@assays$RNA@data)[VariableFeatures(obj), ]

# run Magic
citro.magic <- magic(t(counts.normalized), genes="all_genes", n.jobs = -1, seed = 1994)
citro.magic.data <- citro.magic$result

# compute some correlations
# temp <- parallelDist(as.matrix(citro.magic.data))

pear_corr <- 1 - WGCNA::cor1(t(citro.magic.data), verbose = T)

# run phate
citro.phate <- phate(t(counts.normalized), ndim = 25)
citro.phate.data <- citro.phate$embedding

citro.phate.dist <- parallelDist(citro.phate.data)
```

## SPF No CC
```{r}
# get the counts
counts <- fread("Data/spf_noCC_noNKT.txt") %>% column_to_rownames(var = "V1")
obj <- CreateSeuratObject(counts, project = "Proj", min.cells = 5, min.features = 200)
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^MT-")
obj <- subset(obj, subset = nFeature_RNA > 200 & nFeature_RNA < 12000 & percent.mt < 5)
obj <- NormalizeData(object = obj, normalization.method = "LogNormalize", scale.factor = 10000, verbose = F)
obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 500, verbose = T)

counts.normalized <- as.matrix(obj@assays$RNA@data)[VariableFeatures(obj), ]

# run Magic
spf.noCC.magic <- magic(t(counts.normalized), genes="all_genes", n.jobs = -1, seed = 1994)
spf.noCC.magic.data <- spf.noCC.magic$result

# compute some correlations
# temp <- parallelDist(as.matrix(spf.noCC.magic.data))

pear_corr <- 1 - WGCNA::cor1(t(spf.noCC.magic.data), verbose = T)

# run phate
spf.noCC.phate <- phate(t(counts.normalized), ndim = 2)
spf.noCC.phate.data <- spf.noCC.phate$embedding

spf.noCC.phate.dist <- parallelDist(spf.noCC.phate.data)
```

## SPF All T-Cells
```{r}
# get the counts
counts <- fread("Data/SPF_allTcells.txt") %>% column_to_rownames(var = "V1")
obj <- CreateSeuratObject(counts, project = "Proj", min.cells = 5, min.features = 200)
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^MT-")
obj <- subset(obj, subset = nFeature_RNA > 200 & nFeature_RNA < 12000 & percent.mt < 5)
obj <- NormalizeData(object = obj, normalization.method = "LogNormalize", scale.factor = 10000, verbose = F)
obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 500, verbose = T)

counts.normalized <- as.matrix(obj@assays$RNA@data)[VariableFeatures(obj), ]

# run Magic
spf.magic <- magic(t(counts.normalized), genes="all_genes", n.jobs = -1, seed = 1994)
spf.magic.data <- spf.magic$result

# compute some correlations
# temp <- parallelDist(as.matrix(spf.magic.data))

pear_corr <- 1 - WGCNA::cor1(t(spf.magic.data), verbose = T)

# run phate
spf.phate <- phate(t(counts.normalized), ndim = 2)
spf.phate.data <- spf.phate$embedding

spf.phate.dist <- parallelDist(spf.phate.data)
```