---
title: "Pipeline Analysis"
author: "Elijah Willie"
date: "08/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in required libraries and scripts

```{r }
rm(list = ls())
gc()
suppressPackageStartupMessages({
  library(Seurat)
  library(Seurat)
  library(fastcluster)
  library(parallelDist)
  library(tidyverse)
  library(cluster)
  library(Rclusterpp)
  library(sigclust2)
  library(data.table)
  library("diptest")
  library(Rtsne)
  library(PPCI)
  library(splatter)
  library(SC3)
  library(scater)
  library(SingleCellExperiment)
  library(jackstraw)
  library(parallelDist)
  library(ClassDiscovery)
  library(PCDimension)
  library(irlba)
  library(WGCNA)
  library(Rfast)
}
)
setwd("/home/elijah/Documents/Clusterability")
source("Helper_Functions.R")
source("/home/elijah/Documents/scrna2019/algs/glmpca.R")
source("/home/elijah/Documents/scrna2019/util/functions.R")
source("/home/elijah/Documents/scrna2019/util/functions_genefilter.R")
source("Pipeline_Functions.R")
```

# Read in the datasets

```{r}
citro_counts <- fread("Data/Citro_hash_noCycle_noMyeloid.txt") %>% column_to_rownames(var = "V1")
spf_noCC_counts <- fread("Data/spf_noCC_noNKT.txt") %>% column_to_rownames(var = "V1")
spf_counts <- fread("Data/SPF_allTcells.txt") %>% column_to_rownames(var = "V1")
```
# Seurat analysis on the datasets

## Preprocess the data and select best features
```{r}
citro_seurat <- Preprocess_Data(as.matrix(citro_counts), nFeatures = 500, prop = 0.10)
gc()
spf_noCC_seurat <- Preprocess_Data(as.matrix(spf_noCC_counts),  nFeatures = 500)
gc()
spf_seurat <- Preprocess_Data(as.matrix(spf_counts),  nFeatures = 500)
```

## Run MDH on the data

```{r}
citro_seurat_mdh <- mdh(t(citro_seurat$Seurat.Ob[["RNA"]]@scale.data))
spf_noCC_seurat_mdh <- mdh(t(spf_noCC_seurat$Seurat.Ob[["RNA"]]@scale.data))
spf_seurat_mdh <- mdh(t(spf_seurat$Seurat.Ob[["RNA"]]@scale.data))
```

## Run statistical tests
```{r}
# run tests on the baseline
seurat_modality_base_citro <- Test_Modality(t(citro_seurat$Seurat.Ob[["RNA"]]@scale.data))
# run tests on the reduced data
seurat_modality_pcs_citro <- Test_Modality(citro_seurat$Sig.PCs.Data)
seurat_modality_mdh_citro <- Test_Modality(citro_seurat_mdh$fitted)
gc()

# run tests on the baseline
seurat_modality_base_spf_noCC <- Test_Modality(t(spf_noCC_seurat$Seurat.Ob[["RNA"]]@scale.data))
# run tests on the reduced data
seurat_modality_pcs_spf_noCC <- Test_Modality(spf_noCC_seurat$Sig.PCs.Data)
seurat_modality_mdh_spf_noCC <- Test_Modality(spf_noCC_seurat_mdh$fitted)
gc()

# run tests on the baseline
seurat_modality_base_spf <- Test_Modality(t(spf_seurat$Seurat.Ob[["RNA"]]@scale.data))
# run tests on the reduced data
seurat_modality_pcs_spf <- Test_Modality(spf_seurat$Sig.PCs.Data)
seurat_modality_mdh_spf <- Test_Modality(spf_seurat_mdh$fitted)
```


# SCRNA analysis on the datasets

## Preprocess the data and select best features
```{r}
gc()
citro_scrna <- Preprocess_Data(as.matrix(citro_counts), method = "Multi", nFeatures = 500)
spf_noCC_scrna <- Preprocess_Data(as.matrix(spf_noCC_counts), method = "Multi", nFeatures = 500)
spf_scrna <- Preprocess_Data(as.matrix(spf_counts), method = "Multi", nFeatures = 500)
```

## Do Dimensionality Reduction

```{r}
gc()
citro_scrna_dim_red <- Dim_Reduction(t(citro_scrna$Deviances), nperm = 1000, nPCs = 25, prop = 1.0)
spf_noCC_scrna_dim_red <- Dim_Reduction(t(spf_noCC_scrna$Deviances), nperm = 1000, nPCs = 25, prop = 1.0)
spf_scrna_dim_red <- Dim_Reduction(t(spf_scrna$Deviances), nperm = 1000, nPCs = 25, prop = 1.0)
```

## Run statistical tests
```{r}
# run baseline
scrna_modality_base_citro <- Test_Modality(citro_scrna$Deviances)
# run on sig pcs and mdh
scrna_modality_pcs_citro <- Test_Modality(citro_scrna_dim_red$Sig.PCs)
scrna_modality_mdh_citro <- Test_Modality(citro_scrna_dim_red$MDH$fitted)
gc()

# run baseline
scrna_modality_base_spf_noCC <- Test_Modality(spf_noCC_scrna$Deviances)
# run on sig pcs and mdh
scrna_modality_pcs_spf_noCC <- Test_Modality(spf_noCC_scrna_dim_red$Sig.PCs)
scrna_modality_mdh_spf_noCC <- Test_Modality(spf_noCC_scrna_dim_red$MDH$fitted)
gc()

# run baseline
scrna_modality_base_spf <- Test_Modality(spf_scrna$Deviances)
# run on sig pcs and mdh
scrna_modality_pcs_spf <- Test_Modality(spf_scrna_dim_red$Sig.PCs)
scrna_modality_mdh_spf <- Test_Modality(spf_scrna_dim_red$MDH$fitted)
```

# Benchmark data
## Mouse - Retina
```{r}
# get the counts
counts <- counts(readRDS("Data/Benchmarks/Mouse/Brain/baron_mouse.rds"))

# create a modality object
obj <- CreateModalityObject(counts)
gc()
# add the seurat slot
obj <- PreprocessObject(obj)

# add the scrna slot
obj <- PreprocessObject(obj, method = "Scrna")

# Run the Seurat modality tests
obj <- TestModality(obj)

# estimate k using sc3
# create an sc3 argument from the cleaned data
sc3_sce <- SingleCellExperiment(
    assays = list(counts = obj@Data$cleaned)
)
sc3_sce <- normalize(sc3_sce)

sc3_sce <- sc3_estimate_k(sc3_sce)
sc3_sce@metadata$sc3
```

