---
title: "Special Assignment"
author: "Elijah Willie"
date: "May 2, 2019"
output: html_document
---

# Load in required libraries
```{r}
setwd("/home/elijah/Documents/Clusterability")
rm(list = ls())
#library(sf)
library(Seurat)
library(fastcluster)
library(parallelDist)
library(tidyverse)
library(cluster)
library(Rclusterpp)
library(sigclust2)
library(data.table)
library(dendextend)
library(corrplot)
library(ape)
library(parallel)
library(agricolae)
library(lubridate)
library(factoextra)
library(clustertend)
library(Emcdf)
library("diptest")
library(Rtsne)
library(cluster)
#load helper functions
source("Helper_Functions.R")
source("SigClust_mod.R")
library(dismay)
#source("Consensus_Function.R")
library(pcurve)
library(PPCI)
library(jackstraw)
```


# Run the analyses
```{r}
Darmanis <- fread("Data/Sara_Paper/Darmanis_ROSMAP_Elijah.txt") %>% column_to_rownames(var = "V1") %>% as.matrix()

# remove duplicated columns
genes <- colnames(Darmanis)
Darmanis <- Darmanis[, genes[!duplicated(genes)]]
Darmanis <- as.matrix(t(Darmanis))
# Run the dip test on just the raw pairwise distances

# initialize a pdf document to hold the plots
pdf("Results/Darmanis_Clusterability_Genes_Plots.pdf")

full_dist <- cor(t(Darmanis))

#plot a histogram of the positive correlation values
melted_cor <-setDT(melt(full_dist))[Var1 != Var2, .SD[which.max(value)], keyby=Var1]
hist(melted_cor$value, breaks = 100, main = "Histogram of positive correlation values", xlab = "Correlation", probability = F, col = "lightblue")

full_dist <- as.matrix(full_dist[upper.tri(full_dist, diag = F)])

t#run the dip test
full_dip <- dip.test(full_dist)$p.value

#plot the results
hist(full_dist, breaks = 100, main = paste("Darmanis Density plot genes on Full Data", "\nDip Test p-value =", round(full_dip,4)), xlab = "Correlation", probability = T, col = "lightblue")
lines(density(full_dist), col="red", lwd=2)

# perform PCA and compute the significant PCS

#compute the significant PCs
num_sig <- permutationPA(Darmanis, seed = 1994)

#get the indices of the significant PCs
sig_indices <- which(num_sig$p < 0.05)
if(length(sig_indices) == 0){
  sig_indices <- seq(1, 10, by = 1)
}

#run PCA
PCs <- prcomp(Darmanis)

# Perform the dip test on the first PC

# run the test
dip.test(PCs$x[, 1])

# Run analyses on the significant PCs data
#extract the PCs data
data_pca <- PCs$x[, sig_indices]

#compute the pairwise distances
pca_dist <- cor(t(data_pca))
pca_dist <- as.matrix(pca_dist[upper.tri(pca_dist, diag = F)])

#run the dip test on the distances
dip_stat <- dip.test(pca_dist)$p.value

# plot the results
hist(pca_dist, breaks = 100, main = paste("Darmanis Density plot genes on significant PCs", "\nDip Test p-value =", round(dip_stat,4)), xlab = "Correlation", probability = T, col = "lightblue")
lines(density(pca_dist), col="red", lwd=2)

# Minimum Density Hyperplane using the first PC as the initial projection vector

# get the projection vector
v0 <- PCs$rotation[, 1]

# run the mdh algorithm
sol <- mdh(Darmanis, v0 = v0)

# plot the results
plot(sol)

# compute the dip statistics and plot it
sol_dist <- parallelDist(sol$fitted)
dip_stat <- dip.test(sol_dist)$p.value

plot(sol$fitted[, 1], sol$fitted[, 2], xlab = "Plane 1", ylab = "Plane 2", main = "Minimum density hyperplane data projection")
hist(sol_dist, breaks = 100, main = paste("Darmanis density genes plot on Min Density Hyperplane \n on the first PC", "\nDip Test p-value =", round(dip_stat,4)), xlab = "Distance", probability = T, col = "lightblue")
lines(density(sol_dist), col="red", lwd=2)

# Minimum Density Hyperplane using the significant PCs as the initial projection vector

# get the projection vector
v0 <- PCs$rotation[, sig_indices]

# run the mdh algorithm
sol <- mdh(Darmanis, v0 = v0)

# plot the results
plot(sol)

# compute the dip statistics and plot it
sol_dist <- parallelDist(sol$fitted)
dip_stat <- dip.test(sol_dist)$p.value

plot(sol$fitted[, 1], sol$fitted[, 2], xlab = "Plane 1", ylab = "Plane 2", main = "Minimum density hyperplane data projection")
hist(sol_dist, breaks = 100, main = paste("Darmanis density genes plot on Min Density Hyperplane \n on Significant PCs", "\nDip Test p-value =", round(dip_stat,4)), xlab = "Distance", probability = T, col = "lightblue")
lines(density(sol_dist), col="red", lwd=2)

dev.off()
```


